// for creating hyperlink to retrieve all results for a given library + location code
(function () {
  'use strict';

  angular.module('viewCustom')
  .factory('liblocService', liblocService);

	function liblocService() {

		var liblocs = [	
			{
			lib: 'AJP',
			id: '124011140003941',
			label: 'Arnold Arboretum',
			locations: [
				{ locCode: 'dgh',   locName: 'Dana Greenhouse' },
				{ locCode: 'fol',   locName: 'Folio' },
				{ locCode: 'gen',   locName: 'GEN' },
				{ locCode: 'gena',  locName: 'General Collections Aeon' },
				{ locCode: 'hd',    locName: 'Offsite Storage (HD)' },
				{ locCode: 'hort',  locName: 'Horticulture Crew Office' },
				{ locCode: 'ipm',   locName: 'Integrated Pest Management Office' },
				{ locCode: 'jrnl',  locName: 'Journals' },
				{ locCode: 'overs', locName: 'Oversize' },
				{ locCode: 'plant', locName: 'Plant Information Office' },
				{ locCode: 'prec',  locName: 'Plant Records' },
				{ locCode: 'ref',   locName: 'Reference' },
				{ locCode: 'rr',    locName: 'Reading Room' },
				{ locCode: 'rra',   locName: 'Reading Room Aeon' },
				{ locCode: 'vcenter', locName: 'Visitor Center' },
				{ locCode: 'weld',  locName: 'Botany Arboretum Weld Hill' },
				{ locCode: 'wgh',   locName: 'Weld Hill Greenhouse' }
			]
			},
			{
			lib: 'BER',
			id: '124009990003941',
			label: 'Biblioteca Berenson',
			locations: [
				{ locCode: 'aic',   locName: 'Asian & Islamic Collection' },
				{ locCode: 'auct',   locName: 'Auction Catalogs' },
				{ locCode: 'beren',   locName: 'Berensoniana' },
				{ locCode: 'cdrom',   locName: 'CD-ROMs' },
				{ locCode: 'data',   locName: 'Data drives' },
				{ locCode: 'dep',   locName: 'Deposit' },
				{ locCode: 'dvd',   locName: 'DVDs and DVD-ROMs' },
				{ locCode: 'foto',   locName: 'Fototeca' },
				{ locCode: 'gen',   locName: 'GEN' },
				{ locCode: 'house',   locName: 'House' },
				{ locCode: 'house2',   locName: 'House 2' },
				{ locCode: 'house3',   locName: 'House 3' },
				{ locCode: 'house4',   locName: 'House 4' },
				{ locCode: 'mfrm',   locName: 'Microforms' },
				{ locCode: 'music',   locName: 'Music' },
				{ locCode: 'offp',   locName: 'Offprints' },
				{ locCode: 'papi',   locName: 'Papiniana' },
				{ locCode: 'per',   locName: 'Periodicals' },
				{ locCode: 'rcd',   locName: 'Recording Collection' },
				{ locCode: 'ref',   locName: 'Reference' },
				{ locCode: 'rsv',   locName: 'Reserves' },
				{ locCode: 'spec',   locName: 'Special Collections' },
				{ locCode: 'store',   locName: 'Remote Storage' },
			]
			},
			{
			lib: 'BAK',
			id: '124009300003941',
			label: 'Baker Business',
			locations: [
				{ locCode:'arc',   locName:'Special Collections -- HBS Archives' },
				{ locCode:'arcad', locName:'Special Collections -- HBS Archives (Administrative Records)' },
				{ locCode:'arcfa', locName:'Special Collections -- HBS Archives (Faculty Papers)' },
				{ locCode:'arcre', locName:'Special Collections -- HBS Archives (Archives Research)' },
				{ locCode:'arcth', locName:'Special Collections -- HBS Archives (Theses)' },
				{ locCode:'balc',  locName:'Stamps Reading Room -- Balcony -- Inquire at Service Desk' },
				{ locCode:'black', locName:'Stamps Reading Room -- Little Black Library' },
				{ locCode:'censu', locName:'Stacks -- Census' },
				{ locCode:'chan',  locName:'Special Collections -- HBS Archives (Chandler)' },
				{ locCode:'core',  locName:'Stamps Reading Room -- Core Collection' },
				{ locCode:'corp',  locName:'Special Collections -- Corporate Reports' },
				{ locCode:'dorio', locName:'Special Collections -- Georges F. Doriot Collection' },
				{ locCode:'easer', locName:'Stamps Reading Room -- East Serials' },
				{ locCode:'findr', locName:'Stacks -- Financial Directories' },
				{ locCode:'fol',   locName:'Stacks -- LC Folio Book' },
				{ locCode:'folse', locName:'Stacks -- Folio Serials' },
				{ locCode:'hcref', locName:'Special Collections -- Reference' },
				{ locCode:'hcvis', locName:'Special Collections -- Visual Collection' },
				{ locCode:'hd',    locName:'Offsite Storage (HD)' },
				{ locCode:'hdarc', locName:'Special Collections – HBS Archives – Offsite Storage (HD)' },
				{ locCode:'hdocs', locName:'Special Collections – Baker Old Class Serial – Offsite Storage (HD)' },
				{ locCode:'hisco', locName:'Special Collections -- Office' },
				{ locCode:'index', locName:'Stacks -- Indexes' },
				{ locCode:'krban', locName:'Special Collections -- Kress Collection (Bancroft)' },
				{ locCode:'kress', locName:'Special Collections -- Kress Collection' },
				{ locCode:'krkey', locName:'Special Collections -- Kress Collection (Keynes)' },
				{ locCode:'krmfm', locName:'Special Collections -- Kress Microfilm' },
				{ locCode:'krnet', locName:'Special Collections -- Networked Resource' },
				{ locCode:'krser', locName:'Special Collections -- Kress Serial Collection' },
				{ locCode:'krsmi', locName:'Special Collections -- Kress Collection (Smith)' },
				{ locCode:'manu',  locName:'Special Collections -- Business Manuscripts' },
				{ locCode:'mfrm',  locName:'Stacks -- Microforms' },
				{ locCode:'net',   locName:'Networked Resource' },
				{ locCode:'newbk', locName:'Stamps Reading Room -- New Books' },
				{ locCode:'oc',    locName:'Special Collections -- Baker Old Class' },
				{ locCode:'ocf',   locName:'Special Collections -- Baker Old Class Folio' },
				{ locCode:'ocff',  locName:'Special Collections -- Baker Old Class Flat Folio' },
				{ locCode:'ocs',   locName:'Special Collections -- Baker Old Class Serial' },
				{ locCode:'ocsf',  locName:'Special Collections -- Baker Old Class Serial Folio' },
				{ locCode:'ocsff', locName:'Special Collections -- Baker Old Class Serial Flat Folio' },
				{ locCode:'openres', locName:'Open Reserve' },
				{ locCode:'overs', locName:'Stacks -- LC Oversize' },
				{ locCode:'ref',   locName:'Stamps Reading Room -- Reference (In-library use only)' },
				{ locCode:'res',   locName:'Stamps Reading Room -- Reserves - Inquire at Service Desk' },
				{ locCode:'rota',  locName:'Stamps Reading Room -- Rotating Display' },
				{ locCode:'rrcp',  locName:'Stamps Reading Room -- Current Periodicals' },
				{ locCode:'rrind', locName:'Stamps Reading Room -- Indexes' },
				{ locCode:'rrmed', locName:'Stacks -- Media Collection' },
				{ locCode:'schwa', locName:'Stamps Reading Room -- HBS Art & Artifacts Book Collection' },
				{ locCode:'stlc',  locName:'Stacks -- LC Books' },
				{ locCode:'stlcp', locName:'Stacks -- LC Pamphlets' },
				{ locCode:'stser', locName:'Stacks -- Serials' },
				{ locCode:'thesi', locName:'Stamps Reading Room -- Thesis' },
				{ locCode:'trade', locName:'Special Collections -- Trade Catalogs' }
			]
			},


{
lib: 'ORC',
id: '124010960003941',
label: 'Botany Ames Orchid',
locations: [
	{ locCode: 'arc',   locName: 'Archives' },
{ locCode: 'fol',   locName: 'Fol.' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'mfrm',   locName: 'Microform' },
{ locCode: 'overs',   locName: 'Oversize' },
{ locCode: 'rareb',   locName: 'Rare Book' },
{ locCode: 'ref',   locName: 'REF' }
]
},
{
lib: 'ARN',
id: '124011420003941',
label: 'Botany Arnold (Cambridge)',
locations: [
	{ locCode: 'arc',   locName: 'Archives' },
{ locCode: 'atl',   locName: 'Atlases' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'mapca',   locName: 'Map Case' },
{ locCode: 'mfrm',   locName: 'Microform' },
{ locCode: 'overs',   locName: 'Oversize' },
{ locCode: 'ref',   locName: 'REF' },
{ locCode: 'ts',   locName: 'Tech.Serv.' }
]
},
{
lib: 'ECB',
id: '124011600003941',
label: 'Botany Economic',
locations: [
	{ locCode: 'arc',   locName: 'Archives' },
{ locCode: 'atl',   locName: 'Atlases' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'overs',   locName: 'Oversize' },
{ locCode: 'pam',   locName: 'PAM' },
{ locCode: 'rareb',   locName: 'Rare Book' },
{ locCode: 'ref',   locName: 'REF' },
{ locCode: 'wassa',   locName: 'Wasson Archives' }
]
},
{
lib: 'FAR',
id: '124011780003941',
label: 'Botany Farlow Library',
locations: [
	{ locCode: 'arc',   locName: 'Archives' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'herb',   locName: 'Herbarium' },
{ locCode: 'overs',   locName: 'Oversize' },
{ locCode: 'pam',   locName: 'PAM' },
{ locCode: 'plus',   locName: '+' },
{ locCode: 'rareb',   locName: 'RARE BOOK' },
{ locCode: 'ref',   locName: 'REF' },
{ locCode: 'reffg',   locName: 'REF FG' },
{ locCode: 'rr',   locName: 'RR' },
{ locCode: 'ts',   locName: 'Tech. Serv.' },
{ locCode: 'xover',   locName: 'XOVERSIZE' }
]
},
{
lib: 'ARG',
id: '124012140003941',
label: 'Botany Gray Arnold',
locations: [
	{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'mfrm',   locName: 'Microform' },
{ locCode: 'overs',   locName: 'Oversize' }
]
},
{
lib: 'GRA',
id: '124011960003941',
label: 'Botany Gray Herbarium',
locations: [
	{ locCode: 'arc',   locName: 'Archives' },
{ locCode: 'atl',   locName: 'Atlases' },
{ locCode: 'botco',   locName: 'Bot.Cong.' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'libno',   locName: 'Libn\'s Office' },
{ locCode: 'mapca',   locName: 'Map Case' },
{ locCode: 'mfrm',   locName: 'Microform' },
{ locCode: 'overs',   locName: 'Oversize' },
{ locCode: 'ref',   locName: 'REF' },
{ locCode: 'refof',   locName: 'Reference Office' },
{ locCode: 'ts',   locName: 'Tech. Serv' }
]
},
{
lib: 'CAB',
id: '124012500003941',
label: 'Cabot Science',
locations: [
	{ locCode: 'atl',   locName: 'ATLAS' },
{ locCode: 'av',   locName: 'None' },
{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'cdrom',   locName: 'CDROM' },
{ locCode: 'circd',   locName: 'CIRC DESK' },
{ locCode: 'compm',   locName: 'COMP MAN' },
{ locCode: 'folma',   locName: 'FOLDED MAP' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'map',   locName: 'MAP' },
{ locCode: 'matht',   locName: 'MATH TEXT' },
{ locCode: 'mfic',   locName: 'MICROFICHE' },
{ locCode: 'mflm',   locName: 'None' },
{ locCode: 'overs',   locName: 'OVERSIZE' },
{ locCode: 'rd',   locName: 'Offsite Storage (RD)' },
{ locCode: 'rdscp',   locName: 'Offsite Storage SCP (RD)' },
{ locCode: 'ref',   locName: 'REF' },
{ locCode: 'refde',   locName: 'REF DESK' },
{ locCode: 'res',   locName: 'RESERVE' },
{ locCode: 'ser',   locName: 'Serial' },
{ locCode: 'spec',   locName: 'Special Collections' },
{ locCode: 'tech',   locName: 'Equipment' }
]
},
{
lib: 'HEL',
id: '124014470003941',
label: 'Center for Hellenic Studies',
locations: [
	{ locCode: 'epipap',   locName: 'Epigraphy and Papyrology Reading Room' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'mfic',   locName: 'FICHE' },
{ locCode: 'mflm',   locName: 'FILM' },
{ locCode: 'overs',   locName: 'OVERSIZE' },
{ locCode: 'per',   locName: 'PERIODICALS' },
{ locCode: 'rare',   locName: 'RARE BOOK ROOM' },
{ locCode: 'ref',   locName: 'REF' }
]
},
{
lib: 'DDO',
id: '124015750003941',
label: 'Dumbarton Oaks',
locations: [
	{ locCode: 'brink',   locName: 'Brinkler' },
{ locCode: 'cs',   locName: 'Coins & Seals' },
{ locCode: 'dblfo',   locName: 'DBL-FOLIO' },
{ locCode: 'fol',   locName: 'FOLIO' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'icfa',   locName: 'IMAGE COLLECTIONS AND FIELDWORK ARCHIVES' },
{ locCode: 'jrnfo',   locName: 'JOURNALS FOLIO' },
{ locCode: 'jrnl',   locName: 'JOURNALS' },
{ locCode: 'jrnov',   locName: 'JOURNALS OVERSIZE' },
{ locCode: 'libno',   locName: 'LIBRARIAN\'S OFFICE' },
{ locCode: 'maps',   locName: 'MAPS' },
{ locCode: 'mfic',   locName: 'MICROFICHE' },
{ locCode: 'mflm',   locName: 'MICROFILM' },
{ locCode: 'mhres',   locName: 'MAIN HOUSE RESERVES' },
{ locCode: 'mhstu',   locName: 'MAIN HOUSE STUDY' },
{ locCode: 'overs',   locName: 'OVERSIZE' },
{ locCode: 'rardf',   locName: 'RARE-DBL-FOL' },
{ locCode: 'rare',   locName: 'RARE' },
{ locCode: 'raref',   locName: 'RARE REFERENCE' },
{ locCode: 'rarfo',   locName: 'RARE-FOLIO' },
{ locCode: 'rarma',   locName: 'RARE-MAPS' },
{ locCode: 'rarov',   locName: 'RARE-OVERSZ' },
{ locCode: 'ref',   locName: 'REFERENCE' },
{ locCode: 'refov',   locName: 'REF-OVERSIZE' },
{ locCode: 'ts',   locName: 'TECH SERVICES' },
{ locCode: 'vf',   locName: 'VERT_FILE' }
]
},
{
lib: 'ENV',
id: '124016160003941',
label: 'Environmental Information Center',
locations: [
	{ locCode: 'env',   locName: 'ENV ARCH' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'ref',   locName: 'ENV REF' }
]
},
{
lib: 'MCZ',
id: '124023960003941',
label: 'Ernst Mayr Library',
locations: [
	{ locCode: 'atl',   locName: 'Ref. Atlases' },
{ locCode: 'biol',   locName: 'Biological Labs **CALL MCZ AT 5-2475 TO REQUEST**' },
{ locCode: 'bird',   locName: 'Bird' },
{ locCode: 'cfs',   locName: 'Concord Field Station' },
{ locCode: 'collops',   locName: 'Museum Collections Operations Office' },
{ locCode: 'ento',   locName: 'Entomology Dept.' },
{ locCode: 'fish',   locName: 'Ichthyology Dept.' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'herp',   locName: 'Herp.' },
{ locCode: 'invtp',   locName: 'Invertebrate Paleontology Collection' },
{ locCode: 'invz',   locName: 'Invertebrate Zoology Dept.' },
{ locCode: 'libno',   locName: 'Librarians Office' },
{ locCode: 'mamm',   locName: 'Mammals Dept.' },
{ locCode: 'marin',   locName: 'Marine Invertebrates Collection' },
{ locCode: 'moll',   locName: 'Mollusks Dept.' },
{ locCode: 'ref',   locName: 'Ref.' },
{ locCode: 'refci',   locName: 'Ref. Circ. desk' },
{ locCode: 'res',   locName: 'Reserves' },
{ locCode: 'spec',   locName: 'Spec. Coll.' },
{ locCode: 'specr',   locName: 'Spec. Coll. Ref.' },
{ locCode: 'ts',   locName: 'Tech. Serv.' },
{ locCode: 'vertp',   locName: 'Vertebrate Paleontology Collection' }
]
},
{
lib: 'FAL',
id: '124016390003941',
label: 'Fine Arts Library',
locations: [
{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'fallc',   locName: 'FAL-LC' },
{ locCode: 'falxc',   locName: 'FAL-LC XCAGE' },
{ locCode: 'fogg',   locName: 'Fogg' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdper',   locName: 'FAL Periodicals (HD)' },
{ locCode: 'hdrubper',   locName: 'Rubel Periodicals (HD)' },
{ locCode: 'hdrubvisco',   locName: 'Rubel VisColl Offsite Storage (HD)' },
{ locCode: 'hdsc',   locName: 'Offsite Special Collections (HD)' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'hdvisco',   locName: 'VisColl Offsite Storage (HD)' },
{ locCode: 'micco',   locName: 'MicColl' },
{ locCode: 'nbs',   locName: 'New Book Shelf' },
{ locCode: 'net',   locName: 'Networked Resource' },
{ locCode: 'rd',   locName: 'Offsite Storage (RD)' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'rr',   locName: 'Reading Room' },
{ locCode: 'rubgen',   locName: 'Rubel General Collections' },
{ locCode: 'rubhd',   locName: 'Rubel Offsite Storage (HD)' },
{ locCode: 'rubhdsc',   locName: 'Rubel Offsite Special Collections (HD)' },
{ locCode: 'rublc',   locName: 'RUB-LC' },
{ locCode: 'rubrd',   locName: 'Rubel Offsite Storage (RD)' },
{ locCode: 'rubrr',   locName: 'Rubel Reading Room' },
{ locCode: 'rubvisco',   locName: 'Rubel VisColl' },
{ locCode: 'rubxc',   locName: 'RUB-LC XCAGE' },
{ locCode: 'rubxcage',   locName: 'Rubel XCage' },
{ locCode: 'spec',   locName: 'Special Collections' },
{ locCode: 'visco',   locName: 'VisColl' },
{ locCode: 'xcage',   locName: 'XCage' }
]
},
{
lib: 'DES',
id: '124021890003941',
label: 'Frances Loeb Library',
locations: [
	{ locCode: 'acc',   locName: 'Special Collections ACC' },
{ locCode: 'accov',   locName: 'Special Collections ACC Oversize' },
{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'ce',   locName: 'Special Collections CE' },
{ locCode: 'ceov',   locName: 'Special Collections CE Oversize' },
{ locCode: 'clun',   locName: 'Special Collections Cluny' },
{ locCode: 'cluno',   locName: 'Special Collections Cluny Oversize' },
{ locCode: 'cmr',   locName: 'Special Collections CMR' },
{ locCode: 'cmrfo',   locName: 'Special Collections CMR Folio' },
{ locCode: 'cmrov',   locName: 'Special Collections CMR Oversize' },
{ locCode: 'cons',   locName: 'Conservation' },
{ locCode: 'disp',   locName: 'Display' },
{ locCode: 'fol',   locName: 'Folio' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'gsdfac',   locName: 'GSD Faculty Publications' },
{ locCode: 'gsdpop',   locName: 'GSD Picks' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdsc',   locName: 'Offsite Special Collections (HD)' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'lec',   locName: 'Special Collections Le Corbusier' },
{ locCode: 'lecov',   locName: 'Special Collections Le Corbusier Oversize' },
{ locCode: 'lten',   locName: 'Onsite Storage' },
{ locCode: 'mfic',   locName: 'Microfiche' },
{ locCode: 'mflm',   locName: 'Microfilm' },
{ locCode: 'net',   locName: 'Networked Resource' },
{ locCode: 'openr',   locName: 'Open Reserve' },
{ locCode: 'overs',   locName: 'Oversize' },
{ locCode: 'pamb',   locName: 'Pam Box' },
{ locCode: 'prev',   locName: 'Preservation Review' },
{ locCode: 'rare',   locName: 'Special Collections Rare' },
{ locCode: 'raref',   locName: 'Special Collections Rare Folio' },
{ locCode: 'rarov',   locName: 'Special Collections Rare Oversize' },
{ locCode: 'rarre',   locName: 'Special Collections Rare Reference' },
{ locCode: 'ref',   locName: 'Reference' },
{ locCode: 'refde',   locName: 'Reference Desk' },
{ locCode: 'refol',   locName: 'Reference Folio' },
{ locCode: 'refov',   locName: 'Reference Oversize' },
{ locCode: 'refso',   locName: 'Reference STAT Oversize' },
{ locCode: 'refst',   locName: 'Reference STAT' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'rich',   locName: 'Special Collections Rich' },
{ locCode: 'richf',   locName: 'Special Collections Rich Folio' },
{ locCode: 'richo',   locName: 'Special Collections Rich Oversize' },
{ locCode: 'rri',   locName: 'Special Collections RRI' },
{ locCode: 'rrio',   locName: 'Special Collections RRI Oversize' },
{ locCode: 'stat',   locName: 'Stat' },
{ locCode: 'tfthe',   locName: 'Thesis' },
{ locCode: 'theov',   locName: 'Thesis THEOV' },
{ locCode: 'thesi',   locName: 'Thesis THESI' },
{ locCode: 'vf',   locName: 'VF' },
{ locCode: 'vfo',   locName: 'VF Oversize' },
{ locCode: 'vfp',   locName: 'VF Periodicals' },
{ locCode: 'vfr',   locName: 'VF Reference' },
{ locCode: 'vft',   locName: 'Thesis VFT' },
{ locCode: 'vfto',   locName: 'Thesis VFTO' },
{ locCode: 'visr',   locName: 'Visual Resources' }
]
},
{
lib: 'FUN',
id: '124016800003941',
label: 'Fung Library',
locations: [
	{ locCode: 'dagen',   locName: 'Davis Center for Russian and Eurasian Studies' },
{ locCode: 'dahd',   locName: 'Davis Center for Russian and Eurasian Studies Offsite Storage' },
{ locCode: 'daref',   locName: 'Davis Center for Russian and Eurasian Studies Reference' },
{ locCode: 'dasp',   locName: 'Davis Center for Russian and Eurasian Studies Special Collection' },
{ locCode: 'docd',   locName: 'Documentation Center on Contemporary Japan CD-ROM' },
{ locCode: 'dodvd',   locName: 'Documentation Center on Contemporary Japan DVD' },
{ locCode: 'dogen',   locName: 'Documentation Center on Contemporary Japan' },
{ locCode: 'dohd',   locName: 'Documentation Center on Contemporary Japan Offsite Storage' },
{ locCode: 'doref',   locName: 'Documentation Center on Contemporary Japan Reference' },
{ locCode: 'dovhs',   locName: 'Documentation Center on Contemporary Japan VHS' },
{ locCode: 'facd',   locName: 'Fairbank Center for Chinese Studies CD' },
{ locCode: 'fadvd',   locName: 'Fairbank Center for Chinese Studies DVD' },
{ locCode: 'faflp',   locName: 'Fairbank Center for Chinese Studies FLP' },
{ locCode: 'fagen',   locName: 'Fairbank Center for Chinese Studies' },
{ locCode: 'fahd',   locName: 'Fairbank Center for Chinese Studies Offsite Storage' },
{ locCode: 'fanbs',   locName: 'Fairbank Center for Chinese Studies -- New Books Shelf' },
{ locCode: 'faref',   locName: 'Fairbank Center for Chinese Studies Reference' },
{ locCode: 'fasp',   locName: 'Fairbank Center for Chinese Studies Special Collection' },
{ locCode: 'fausd',   locName: 'Fairbank Center for Chinese Studies U.S.Doc' },
{ locCode: 'favcd',   locName: 'Fairbank Center for Chinese Studies VCD' },
{ locCode: 'favf',   locName: 'Fairbank Center for Chinese Studies VF' },
{ locCode: 'faybk',   locName: 'Fairbank Center for Chinese Studies Yearbooks' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdda',   locName: 'Davis Center for Russian and Eurasian Studies Offsite Storage (HD)' },
{ locCode: 'hddas',   locName: 'Davis Center for Russian and Eurasian Studies Special Coll. (HD)' },
{ locCode: 'hddo',   locName: 'Documentation Center on Contemporary Japan Offsite Storage (HD)' },
{ locCode: 'hdfa',   locName: 'Fairbank Center for Chinese Studies Offsite Storage (HD)' },
{ locCode: 'ref',   locName: 'Reference' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'vid',   locName: 'Video' }
]
},
			{
			lib: 'MED',
			id: '124013600003941',
			label: 'Countway Medicine',
			locations: [
				{ locCode: 'arc',   locName: 'Archives' },
				{ locCode: 'bind',   locName: 'Bindery' },
				{ locCode: 'chc',   locName: 'Consumer Health Collection' },
				{ locCode: 'cydhl',   locName: 'Children Youth Books Collection' },
				{ locCode: 'dib',   locName: 'Diversity, Inclusion and Belonging Coll' },
				{ locCode: 'display',   locName: 'Information desk' },
				{ locCode: 'f',   locName: 'f' },
				{ locCode: 'fanon',   locName: 'Fanon' },
				{ locCode: 'gen',   locName: 'GEN' },
				{ locCode: 'gmd',   locName: 'Graphic Medicine Collection' },
				{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
				{ locCode: 'hdrb',   locName: 'Offsite Storage Rare Books (HD)' },
				{ locCode: 'him',   locName: 'Humanities in Medicine' },
				{ locCode: 'holm',   locName: 'Holmes Collection' },
				{ locCode: 'jcsw',   locName: 'JCSW Women and Medicine' },
				{ locCode: 'mfrm',   locName: 'Microform Room' },
				{ locCode: 'net',   locName: 'Networked Resource' },
				{ locCode: 'rareb',   locName: 'Rare Books' },
				{ locCode: 'raref',   locName: 'Rare Books f' },
				{ locCode: 'rarff',   locName: 'Rare Books ff' },
				{ locCode: 'rarre',   locName: 'Rare Books Reference' },
				{ locCode: 'rarrf',   locName: 'Rare Books Reference f' },
				{ locCode: 'rbfff',   locName: 'Rare Books fff' },
				{ locCode: 'rbrecon',   locName: 'Rare Book Recon Project' },
				{ locCode: 'ref1',   locName: 'Ref.' },
				{ locCode: 'res',   locName: 'Reserve' },
				{ locCode: 'russ',   locName: 'Russell Reading Room' }
			]
			},
			{
			lib: 'HUA',
			id: '124017720003941',
			label: 'Harvard University Archives',
			locations: [
				{ locCode:'gen',   locName:'GEN' },
				{ locCode:'hd',    locName:'Offsite Storage (HD)' },
				{ locCode:'net',   locName:'Offline Digital' },
				{ locCode:'refde', locName:'Reference Desk' },
				{ locCode:'rr',    locName:'Reading Room' },
				{ locCode:'vault', locName:'Vault' }
			]
			},
			{
lib: 'GUT',
id: '124017490003941',
label: 'Gutman Education',
locations: [
	{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'cir',   locName: 'Circulation Desk' },
{ locCode: 'dis',   locName: 'Display Second Floor' },
{ locCode: 'equ',   locName: 'Equipment' },
{ locCode: 'gen',   locName: 'General Collections' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdmed',   locName: 'Offsite Storage Media (HD)' },
{ locCode: 'hdmfrm',   locName: 'Offsite Storage Microforms (HD)' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'hdspec',   locName: 'Offsite Storage SPEC (HD)' },
{ locCode: 'hdspeca',   locName: 'Offsite Storage SPECA (HD)' },
{ locCode: 'hdspecc',   locName: 'Offsite Storage SPECC (HD)' },
{ locCode: 'hdspech',   locName: 'Offsite Storage SPECH (HD)' },
{ locCode: 'hdspecl',   locName: 'Offsite Storage SPECL (HD)' },
{ locCode: 'hdspect',   locName: 'Offsite Storage SPECT (HD)' },
{ locCode: 'hdspecu',   locName: 'Offsite Storage SPECU (HD)' },
{ locCode: 'hdtest',   locName: 'Offsite Storage TEST (HD)' },
{ locCode: 'juv',   locName: 'Children and Young Adult Collection' },
{ locCode: 'mfic',   locName: 'MFiche' },
{ locCode: 'mficp',   locName: 'MFiche Per.' },
{ locCode: 'mflm',   locName: 'MFilm' },
{ locCode: 'mflmp',   locName: 'MFilm Per.' },
{ locCode: 'per',   locName: 'Periodicals' },
{ locCode: 'rd',   locName: 'Offsite Storage (RD)' },
{ locCode: 'rdmfrm',   locName: 'Offsite Storage Microforms (RD)' },
{ locCode: 'rdscp',   locName: 'Offsite Storage SCP (RD)' },
{ locCode: 'ref',   locName: 'Reference' },
{ locCode: 'refte',   locName: 'Ref. Tests' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'speco',   locName: 'Special Collections Office' },
{ locCode: 'sqp',   locName: 'SQP' },
{ locCode: 'testr',   locName: 'Reserve Tests' }
]
},
{
lib: 'ART',
id: '124019000003941',
label: 'Harvard Art Museums',
locations: [
	{ locCode: 'arc',   locName: 'Archives' },
{ locCode: 'brm',   locName: 'Busch-Reisinger Museum' },
{ locCode: 'fogg',   locName: 'Fogg Art Museum' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'mong',   locName: 'Mongan Center' }
]
},
{
lib: 'DIV',
id: '124008740003941',
label: 'Harvard Divinity School Library',
locations: [
	{ locCode: 'arc',   locName: 'Special Coll. -- Reference' },
{ locCode: 'atl',   locName: 'Atlas Stand' },
{ locCode: 'dsc',   locName: 'DISCARDED' },
{ locCode: 'facbk',   locName: 'Faculty Books' },
{ locCode: 'fol',   locName: 'Folio' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdbb',   locName: 'Offsite Storage Brittle Book (HD)' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'hdsp',   locName: 'Special Coll. (HDSP) -- Offsite Storage (HD)' },
{ locCode: 'hdspf',   locName: 'Special Coll. (HDSPF) -- Offsite Storage folio (HD)' },
{ locCode: 'hdspp',   locName: 'Special Coll. (HDSPP) -- Offsite Storage port. (HD)' },
{ locCode: 'hdspt',   locName: 'Special Coll. (HDSPT) -- Tillich --Offsite Storage (HD)' },
{ locCode: 'lst',   locName: 'LOST' },
{ locCode: 'lstsc',   locName: 'Special Coll. -- LOST' },
{ locCode: 'med',   locName: 'Media' },
{ locCode: 'mfic',   locName: 'Mfiche' },
{ locCode: 'mflm',   locName: 'Mflm.' },
{ locCode: 'mflminbox',   locName: 'Offsite boxed microfilm collection' },
{ locCode: 'ms',   locName: 'Special Coll. -- Manuscripts & Archives' },
{ locCode: 'net',   locName: 'Networked Resource' },
{ locCode: 'oldd',   locName: 'OLD DIV' },
{ locCode: 'olddf',   locName: 'OLD DIV folio' },
{ locCode: 'olddp',   locName: 'OLD DIV port.' },
{ locCode: 'pam',   locName: 'Pamph.' },
{ locCode: 'pamf',   locName: 'Pamph. folio' },
{ locCode: 'pamp',   locName: 'Pamph. port.' },
{ locCode: 'prr',   locName: 'Periodicals Reading Room' },
{ locCode: 'rd',   locName: 'Offsite Storage (RD)' },
{ locCode: 'ref',   locName: 'Ref.' },
{ locCode: 'refcd',   locName: 'Ref. CD-ROM' },
{ locCode: 'refol',   locName: 'Ref. folio' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'schan',   locName: 'Special Coll. -- Channing Library' },
{ locCode: 'spam',   locName: 'Special Coll. -- Pamphlets' },
{ locCode: 'spamf',   locName: 'Special Coll. -- Pamphlets folio' },
{ locCode: 'spamp',   locName: 'Special Coll. -- Pamphlets port.' },
{ locCode: 'spec',   locName: 'Special Coll.' },
{ locCode: 'specf',   locName: 'Special Coll. folio' },
{ locCode: 'specp',   locName: 'Special Coll. port.' },
{ locCode: 'srbt',   locName: 'Special Coll. -- R.B.R. tracts' },
{ locCode: 'srbtf',   locName: 'Special Coll. -- R.B.R. tracts folio' },
{ locCode: 'still',   locName: 'Special Coll. -- Tillich Archive' },
{ locCode: 'stss',   locName: 'Special Coll. -- TSS' }
]
},
{
lib: 'HFA',
id: '124018130003941',
label: 'Harvard Film Archive',
locations: [
	{ locCode: 'filem',   locName: 'FILEM' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' }
]
},
{
lib: 'KSG',
id: '124018540003941',
label: 'Harvard Kennedy School',
locations: [
	{ locCode: 'arc',   locName: 'Archives' },
{ locCode: 'bjr',   locName: 'Bound Journals Room' },
{ locCode: 'brd',   locName: 'Board Games' },
{ locCode: 'cal',   locName: '1-day Tech Lending' },
{ locCode: 'cd',   locName: 'Circ Desk CD-ROM' },
{ locCode: 'cdcdc',   locName: 'Circ Desk CD Case' },
{ locCode: 'cdrom',   locName: 'CD-ROM' },
{ locCode: 'cdvc',   locName: 'Circ Desk Video Case' },
{ locCode: 'cdvid',   locName: 'Circ Desk Video' },
{ locCode: 'chb',   locName: 'Children\'s Books' },
{ locCode: 'dib',   locName: 'Community Voices & Perspectives Collection' },
{ locCode: 'dvd',   locName: 'DVD Collection' },
{ locCode: 'equ',   locName: '3-hour Tech Lending' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdarc',   locName: 'Offsite Storage ARC (HD)' },
{ locCode: 'ksgth',   locName: 'HKS Thesis' },
{ locCode: 'legre',   locName: 'Legal Ref' },
{ locCode: 'mfic',   locName: 'M-Fiche' },
{ locCode: 'new',   locName: 'New Books' },
{ locCode: 'rand',   locName: 'RAND Collection' },
{ locCode: 'ref',   locName: 'Ref' },
{ locCode: 'refin',   locName: 'Ref Index' },
{ locCode: 'refof',   locName: 'Ref Office' },
{ locCode: 'refp',   locName: 'Ref Pillars' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'ts',   locName: 'Tech Services' },
{ locCode: 'wpc',   locName: 'Working Papers Collection' }
]
},
{
lib: 'LAW',
id: '124021100003941',
label: 'Harvard Law School Library',
locations: [
	{ locCode: 'art',   locName: 'Art' },
{ locCode: 'av',   locName: 'A/V' },
{ locCode: 'casua',   locName: 'Casual Reading' },
{ locCode: 'colin',   locName: 'None' },
{ locCode: 'comla',   locName: 'Computer Lab' },
{ locCode: 'fac',   locName: 'Faculty' },
{ locCode: 'ftl',   locName: 'Library Projects' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'genhs',   locName: 'None' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdart',   locName: 'Offsite Storage Art (HD)' },
{ locCode: 'hddrc',   locName: 'Dark Archive HD' },
{ locCode: 'hdhsc',   locName: 'Offsite Special Collections (HD)' },
{ locCode: 'hdrar',   locName: 'Offsite Storage Rare (HD)' },
{ locCode: 'hdred',   locName: 'Offsite Storage Red (HD)' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'hdsov',   locName: 'Offsite Soviet (HD)' },
{ locCode: 'hscso',   locName: 'Soviet Special Collections' },
{ locCode: 'ils',   locName: 'ILS' },
{ locCode: 'ilsrd',   locName: 'ILS Ref Desk' },
{ locCode: 'ilsrr',   locName: 'ILS RR' },
{ locCode: 'ilsvf',   locName: 'ILS V/F' },
{ locCode: 'islar',   locName: 'Islamic Ref' },
{ locCode: 'lvdrc',   locName: 'Dark Archive Louisville' },
{ locCode: 'mfrm',   locName: 'Mic' },
{ locCode: 'micre',   locName: 'Mic Ref' },
{ locCode: 'mss',   locName: 'MSS' },
{ locCode: 'net',   locName: 'Networked Resource' },
{ locCode: 'netlocal',   locName: 'Networked Resource - available via local HLS network' },
{ locCode: 'off',   locName: 'Office' },
{ locCode: 'paint',   locName: 'Paintings' },
{ locCode: 'rare',   locName: 'Rare' },
{ locCode: 'rd',   locName: 'Offsite Storage (RD)' },
{ locCode: 'rdscp',   locName: 'Offsite Storage SCP (RD)' },
{ locCode: 'red',   locName: 'Red Set' },
{ locCode: 'ref',   locName: 'Reference' },
{ locCode: 'refde',   locName: 'Ref Desk' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'root',   locName: 'Root' },
{ locCode: 'sgc',   locName: 'Study Guide Collection' },
{ locCode: 'specr',   locName: 'Special Coll Ref' },
{ locCode: 'ts',   locName: 'TechServ' },
{ locCode: 'vf',   locName: 'V/F' }
]
},
{
lib: 'MAP',
id: '124022630003941',
label: 'Harvard Map Collection',
locations: [
	{ locCode: 'cdmap',   locName: 'CDISC MAP-LC' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'maplc',   locName: 'MAP-LC' },
{ locCode: 'rd',   locName: 'Offsite Storage (RD)' },
{ locCode: 'refml',   locName: 'REF MAP-LC' }
]
},
{
lib: 'HYL',
id: '124019360003941',
label: 'Harvard Yenching Library',
locations: [
	{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'c',   locName: '(C)' },
{ locCode: 'cassw',   locName: 'Cassette Tape (W)' },
{ locCode: 'cdc',   locName: 'CD (C)' },
{ locCode: 'cdj',   locName: 'CD (J)' },
{ locCode: 'cdk',   locName: 'CD (K)' },
{ locCode: 'cdrc',   locName: 'CD-ROM (C)' },
{ locCode: 'cdrj',   locName: 'CD-ROM (J)' },
{ locCode: 'cdrk',   locName: 'CD-ROM (K)' },
{ locCode: 'cdrw',   locName: 'CD-ROM (W)' },
{ locCode: 'cdv',   locName: 'CD (V)' },
{ locCode: 'dvdc',   locName: 'DVD (C)' },
{ locCode: 'dvdj',   locName: 'DVD (J)' },
{ locCode: 'dvdk',   locName: 'DVD (K)' },
{ locCode: 'dvdv',   locName: 'DVD (V)' },
{ locCode: 'dvdw',   locName: 'DVD (W)' },
{ locCode: 'gamej',   locName: 'Games (J)' },
{ locCode: 'gamek',   locName: 'Games (K)' },
{ locCode: 'gamew',   locName: 'Games (W)' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hart',   locName: 'Hart Collection' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdc',   locName: 'Offsite Storage C (HD)' },
{ locCode: 'hdj',   locName: 'Offsite Storage J (HD)' },
{ locCode: 'hdk',   locName: 'Offsite Storage K (HD)' },
{ locCode: 'hdmo',   locName: 'Offsite Storage MO (HD)' },
{ locCode: 'hdrar',   locName: 'Offsite Special Collections R (HD)' },
{ locCode: 'hdraw',   locName: 'Offsite Special Collections W (HD)' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'hdv',   locName: 'Offsite Storage V (HD)' },
{ locCode: 'hdw',   locName: 'Offsite Storage W (HD)' },
{ locCode: 'j',   locName: '(J)' },
{ locCode: 'k',   locName: '(K)' },
{ locCode: 'mfic',   locName: 'Microfiche' },
{ locCode: 'mflm',   locName: 'Microfilm' },
{ locCode: 'mo',   locName: '(MO)' },
{ locCode: 'nbs',   locName: 'New Book Shelf' },
{ locCode: 'rareb',   locName: 'Rare Book' },
{ locCode: 'rarej',   locName: 'Rare (J)' },
{ locCode: 'rarek',   locName: 'Rare (K)' },
{ locCode: 'rarew',   locName: 'Rare (W)' },
{ locCode: 'rd',   locName: 'Offsite Storage (RD)' },
{ locCode: 'rdc',   locName: 'Offsite Storage C (RD)' },
{ locCode: 'rdj',   locName: 'Offsite Storage J (RD)' },
{ locCode: 'rdk',   locName: 'Offsite Storage K (RD)' },
{ locCode: 'rdrar',   locName: 'Offsite Special Collections R (RD)' },
{ locCode: 'rdraw',   locName: 'Offsite Special Collections W (RD)' },
{ locCode: 'rdscp',   locName: 'Offsite Storage SCP (RD)' },
{ locCode: 'rdv',   locName: 'Offsite Storage V (RD)' },
{ locCode: 'rdw',   locName: 'Offsite Storage W (RD)' },
{ locCode: 'refc',   locName: 'Ref (C)' },
{ locCode: 'refj',   locName: 'Ref (J)' },
{ locCode: 'refk',   locName: 'Ref (K)' },
{ locCode: 'refv',   locName: 'Ref (V)' },
{ locCode: 'refw',   locName: 'Ref (W)' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'v',   locName: '(V)' },
{ locCode: 'vcdc',   locName: 'VCD (C)' },
{ locCode: 'vcdw',   locName: 'VCD (W)' },
{ locCode: 'vidc',   locName: 'Video Tape (C)' },
{ locCode: 'vidj',   locName: 'Video Tape (J)' },
{ locCode: 'vidk',   locName: 'Video Tape (K)' },
{ locCode: 'vidw',   locName: 'Video Tape (W)' },
{ locCode: 'w',   locName: '(W)' }
]
},
{
lib: 'HOU',
id: '124020280003941',
label: 'Houghton Library',
locations: [
	{ locCode: 'as',   locName: 'AS' },
{ locCode: 'b',   locName: 'b' },
{ locCode: 'blue',   locName: '(Part of the Woodberry Poetry Collection)' },
{ locCode: 'blueb',   locName: 'Blue Star b (part of the Woodberry Poetry Room)' },
{ locCode: 'bluef',   locName: 'Blue Star f (part of the Woodberry Poetry Room)' },
{ locCode: 'bluep',   locName: 'Blue Star p (part of the Woodberry Poetry Room)' },
{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'f',   locName: 'f' },
{ locCode: 'g',   locName: 'g' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'genhrz',   locName: 'gen (horz)' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdblu',   locName: 'Offsite Storage (Part of the Woodberry Poetry Collection) (HD)' },
{ locCode: 'hlcf',   locName: 'HOU-LC f' },
{ locCode: 'hlcp',   locName: 'HOU-LC p' },
{ locCode: 'hlcpf',   locName: 'HOU-LC pf' },
{ locCode: 'houlc',   locName: 'HOU-LC' },
{ locCode: 'hydb',   locName: 'Hyde Collection b' },
{ locCode: 'hyde',   locName: 'Hyde Collection' },
{ locCode: 'hydf',   locName: 'Hyde Collection f' },
{ locCode: 'hydp',   locName: 'Hyde Collection p' },
{ locCode: 'hydpf',   locName: 'Hyde Collection pf' },
{ locCode: 'm',   locName: 'm' },
{ locCode: 'manu',   locName: 'Manuscript Department' },
{ locCode: 'p',   locName: 'p' },
{ locCode: 'pf',   locName: 'pf' },
{ locCode: 'pfbr',   locName: 'pf (br)' },
{ locCode: 'pfc',   locName: 'PF Cabinet' },
{ locCode: 'pfd',   locName: 'PFD Case Range-half drawer' },
{ locCode: 'pfhrz',   locName: 'pf (horz)' },
{ locCode: 'pp',   locName: 'pp' },
{ locCode: 'ppf',   locName: 'PPF Case Range-full drawer' },
{ locCode: 'roos',   locName: 'Roosevelt' },
{ locCode: 'rr',   locName: 'Reading Room' },
{ locCode: 'rrf',   locName: 'Reading Room f' },
{ locCode: 'solid',   locName: 'SOLIDAR BIBL CTR' },
{ locCode: 'trc',   locName: 'TRC' },
{ locCode: 'trcb',   locName: 'TRC b' },
{ locCode: 'trcf',   locName: 'TRC f' },
{ locCode: 'trclc',   locName: 'TRC-LC' },
{ locCode: 'trcpf',   locName: 'TRC pf' },
{ locCode: 'trlcf',   locName: 'TRC-LC f' },
{ locCode: 'ts',   locName: 'Technical Services' },
{ locCode: 'vault',   locName: 'Vault' },
{ locCode: 'wid',   locName: 'Harry Elkins Widener Collection' },
{ locCode: 'widf',   locName: 'Harry Elkins Widener Collection f' },
{ locCode: 'widpf',   locName: 'Harry Elkins Widener Collection pf' },
{ locCode: 'z',   locName: 'Z-Closet' }
]
},
{
lib: 'KIR',
id: '124020460003941',
label: 'Kirkland House',
locations: [
	{ locCode: 'arc',   locName: 'Archives' },
{ locCode: 'arcov',   locName: 'Archives Oversize' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'mast',   locName: 'Masters Residence' },
{ locCode: 'overs',   locName: 'Oversize' },
{ locCode: 'ref',   locName: 'REF' }
]
},
{
lib: 'LAM',
id: '124020870003941',
label: 'Lamont Library',
locations: [
	{ locCode: 'cdrom',   locName: 'CD-ROM' },
{ locCode: 'doccd',   locName: 'DOC CD-ROM' },
{ locCode: 'doccode',   locName: 'DOCCODE' },
{ locCode: 'docdi',   locName: 'DOC Disk' },
{ locCode: 'docgen',   locName: 'DOCGEN' },
{ locCode: 'dochd',   locName: 'DOC Offsite Storage (HD)' },
{ locCode: 'doclc',   locName: 'DOCLC' },
{ locCode: 'docrd',   locName: 'DOC Offsite Storage (RD)' },
{ locCode: 'docref',   locName: 'DOCREF' },
{ locCode: 'docscan',   locName: 'DOCSCAN' },
{ locCode: 'dvd',   locName: 'DVD' },
{ locCode: 'farns',   locName: 'FARNSWORTH' },
{ locCode: 'fcorl',   locName: 'FARNSWORTH CORLISS LAMONT COLLECTION' },
{ locCode: 'fover',   locName: 'FARNSWORTH OVERSIZE' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'libno',   locName: 'Librarian\'s Office' },
{ locCode: 'miccd',   locName: 'None' },
{ locCode: 'micdi',   locName: 'None' },
{ locCode: 'micgen',   locName: 'MICGEN' },
{ locCode: 'michd',   locName: 'MIC Offsite Storage (HD)' },
{ locCode: 'micrd',   locName: 'MIC Offsite Storage (RD)' },
{ locCode: 'micref',   locName: 'MICREF' },
{ locCode: 'mrs',   locName: 'Media' },
{ locCode: 'mrsau',   locName: 'Media Audiocassette' },
{ locCode: 'mrscd',   locName: 'Media CD' },
{ locCode: 'mrsdv',   locName: 'Media DVD' },
{ locCode: 'mrslp',   locName: 'Media LP' },
{ locCode: 'mrsof',   locName: 'Media Office' },
{ locCode: 'mrsov',   locName: 'Media Oversize' },
{ locCode: 'mrssc',   locName: 'Media Score' },
{ locCode: 'mrsv',   locName: 'Media Video' },
{ locCode: 'mrsvd',   locName: 'Media Videodisc' },
{ locCode: 'nbs',   locName: 'New Book Shelf' },
{ locCode: 'poecass',   locName: 'POECASS' },
{ locCode: 'poecd',   locName: 'POECD' },
{ locCode: 'poecdrom',   locName: 'POECDROM' },
{ locCode: 'poedat',   locName: 'POEDAT' },
{ locCode: 'poedisc',   locName: 'POEDISC' },
{ locCode: 'poedvd',   locName: 'POEDVD' },
{ locCode: 'poegen',   locName: 'POEGEN' },
{ locCode: 'poemedia',   locName: 'POEMEDIA' },
{ locCode: 'poeref',   locName: 'POEREF' },
{ locCode: 'poeser',   locName: 'POESER' },
{ locCode: 'poetapea',   locName: 'POETAPEA' },
{ locCode: 'poevid',   locName: 'POEVID' },
{ locCode: 'ready',   locName: 'REFERENCE READY REF' },
{ locCode: 'ref',   locName: 'REFERENCE' },
{ locCode: 'refof',   locName: 'REFERENCE OFFICE' },
{ locCode: 'res',   locName: 'Reserves' },
{ locCode: 'resdv',   locName: 'Reserves DVD' },
{ locCode: 'ts',   locName: 'Tech. Services' }
]
},
{
lib: 'MUS',
id: '124022400003941',
label: 'Loeb Music Library',
locations: [
	{ locCode: '2dflw',   locName: '2nd floor workroom' },
{ locCode: 'aldr',   locName: 'Aldrich Room' },
{ locCode: 'arcwm',   locName: 'Archive of World Music' },
{ locCode: 'arcwma',   locName: 'Archive of World Music Special Collections' },
{ locCode: 'awmhda',   locName: 'Archive of World Music Offsite Storage (HD)' },
{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hda',   locName: 'Offsite Storage A (HD)' },
{ locCode: 'hdawmhou',   locName: 'Archive of World Music Offsite Storage (HD) - for use in Houghton Library' },
{ locCode: 'hdisham',   locName: 'Offsite Storage Isham Lib. (HD)' },
{ locCode: 'hdmerrhou',   locName: 'Merritt Room Offsite Storage (HD) - for use in Houghton Library' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'hiphop',   locName: 'Hip Hop Archive' },
{ locCode: 'isa',   locName: 'Isham Lib. Special Collections' },
{ locCode: 'isham',   locName: 'Isham Lib.' },
{ locCode: 'merr',   locName: 'Merritt Room' },
{ locCode: 'merrhd',   locName: 'Merritt Room Offsite Storage (HD)' },
{ locCode: 'merrhou',   locName: 'Merritt Room - for use in Houghton Library' },
{ locCode: 'pubsv',   locName: 'Public Services' },
{ locCode: 'recchda',   locName: 'Record Coll. Special Collections Offsite Storage (HD)' },
{ locCode: 'recco',   locName: 'Record Coll.' },
{ locCode: 'reccoa',   locName: 'Record Coll. Special Collections' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'seeg',   locName: 'Seeger Room' },
{ locCode: 'spald',   locName: 'Spalding Room' }
]
},
{
lib: 'PHY',
id: '124025370003941',
label: 'Physics Reading Room',
locations: [
	{ locCode: 'rareb',   locName: 'Rare Books' },
{ locCode: 'rr',   locName: 'Reading Room' }
]
},
{
lib: 'PHI',
id: '124027240003941',
label: 'Robbins Philosophy',
locations: [
	{ locCode: 'bech',   locName: 'Bechtel' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'glass',   locName: 'Glass Case' },
{ locCode: 'kierk',   locName: 'Kierk' },
{ locCode: 'ref',   locName: 'Ref.' },
{ locCode: 'spec',   locName: 'Special Collections' }
]
},
{
lib: 'SCH',
id: '124028520003941',
label: 'Schlesinger Library',
locations: [
	{ locCode: 'etiq',   locName: 'Etiq.' },
{ locCode: 'gen',   locName: 'In-library use only' },
{ locCode: 'hd',   locName: 'Offsite Storage -- In-library use only (HD)' },
{ locCode: 'net',   locName: 'Networked Resource' },
{ locCode: 'pam',   locName: 'Pamphlets' },
{ locCode: 'per',   locName: 'Periodicals Collection (onsite) -- in library use only' },
{ locCode: 'rca',   locName: 'In-library use only RCA' },
{ locCode: 'ref',   locName: 'Ref.' },
{ locCode: 'vault',   locName: 'Vault' },
{ locCode: 'womrc',   locName: 'Woman\'s Rights Collection' }
]
},
{
lib: 'SMY',
id: '124029440003941',
label: 'Smyth Classical Library',
locations: [
	{ locCode: 'corr',   locName: 'Corridor' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'pal',   locName: 'Paleog. Coll.' }
]
},
{
lib: 'SCC',
id: '124030770003941',
label: 'Straus Center for Conservation',
locations: [
	{ locCode: 'cdrom',   locName: 'CD-ROM' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'ref',   locName: 'REF' },
{ locCode: 'ser',   locName: 'Serial' },
{ locCode: 'thesi',   locName: 'Thesis' },
{ locCode: 'vid',   locName: 'Video' }
]
},
{
lib: 'THE',
id: '124030950003941',
label: 'Theatre Collection',
locations: [
	{ locCode: 'actht',   locName: 'Act.Ed. HTC-LC' },
{ locCode: 'as',   locName: 'AS' },
{ locCode: 'b',   locName: 'b' },
{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'bpf',   locName: 'bpf' },
{ locCode: 'f',   locName: 'f' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'genhrz',   locName: 'gen (horz)' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'htclc',   locName: 'HTC-LC' },
{ locCode: 'm',   locName: 'm' },
{ locCode: 'pf',   locName: 'pf' },
{ locCode: 'pfd',   locName: 'PFD Case Range-half drawer' },
{ locCode: 'pfhrz',   locName: 'pf (horz)' },
{ locCode: 'post',   locName: 'Poster' },
{ locCode: 'pp',   locName: 'pp' },
{ locCode: 'ppf',   locName: 'PPF Case Range-full drawer' },
{ locCode: 'rr',   locName: 'Reading Room' },
{ locCode: 'rrf',   locName: 'Reading Room f' },
{ locCode: 'tlcb',   locName: 'HTC-LC b' },
{ locCode: 'tlcf',   locName: 'HTC-LC f' },
{ locCode: 'tlcp',   locName: 'HTC-LC p' },
{ locCode: 'tlcpf',   locName: 'HTC-LC pf' },
{ locCode: 'z',   locName: 'Objects' }
]
},
{
lib: 'TOZ',
id: '124031180003941',
label: 'Tozzer',
locations: [
	{ locCode: 'atl',   locName: 'ATL.' },
{ locCode: 'atllc',   locName: 'ATL. TOZ-LC' },
{ locCode: 'av',   locName: 'A.V.' },
{ locCode: 'avlc',   locName: 'A.V. TOZ-LC' },
{ locCode: 'carrel',   locName: 'Library Carrel' },
{ locCode: 'cas8l',   locName: 'Case 8 TOZ-LC' },
{ locCode: 'case8',   locName: 'Case 8' },
{ locCode: 'com',   locName: 'COMPUTER' },
{ locCode: 'comlc',   locName: 'COMPUTER TOZ-LC' },
{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'hdlc',   locName: 'Offsite Storage TOZ-LC (HD)' },
{ locCode: 'hdsp',   locName: 'Offsite Storage SPEC.COLL. (HD)' },
{ locCode: 'hdspl',   locName: 'Offsite Storage SPEC.COLL. TOZ-LC (HD)' },
{ locCode: 'hold',   locName: 'Assigned Hold Shelves' },
{ locCode: 'ikc',   locName: 'Indigenous Knowledge Collection' },
{ locCode: 'map',   locName: 'MAPS' },
{ locCode: 'maplc',   locName: 'MAPS TOZ-LC' },
{ locCode: 'mcrd',   locName: 'Microcard' },
{ locCode: 'mfclc',   locName: 'Microfiche TOZ-LC' },
{ locCode: 'mfic',   locName: 'Microfiche' },
{ locCode: 'mficr',   locName: 'Microfiche REF' },
{ locCode: 'mflm',   locName: 'Microfilm' },
{ locCode: 'mfmlc',   locName: 'Microfilm TOZ-LC' },
{ locCode: 'rd',   locName: 'Offsite Storage (RD)' },
{ locCode: 'rdlc',   locName: 'Offsite Storage TOZ-LC (RD)' },
{ locCode: 'rdsp',   locName: 'Offsite Storage SPEC.COLL. (RD)' },
{ locCode: 'rdspl',   locName: 'Offsite Storage SPEC.COLL. TOZ-LC (RD)' },
{ locCode: 'ref',   locName: 'REF' },
{ locCode: 'res',   locName: 'Reserve' },
{ locCode: 'spec',   locName: 'SPEC.COLL.' },
{ locCode: 'splc',   locName: 'SPEC.COLL. TOZ-LC' },
{ locCode: 'tozlc',   locName: 'TOZ-LC' }
]
},
{
lib: 'URI',
id: '124031460003941',
label: 'Ukranian Research Institute Library',
locations: [
	{ locCode: 'gen',   locName: 'GEN' },
{ locCode: 'hd',   locName: 'Offsite Storage (HD)' },
{ locCode: 'ref',   locName: 'Ref' }
]
},
{
lib: 'WID',
id: '124032000003941',
label: 'Widener Library',
locations: [
	{ locCode: 'bound',   locName: 'Bound-with / Analyzed' },
{ locCode: 'carrel',   locName: 'Library Carrel' },
{ locCode: 'colde',   locName: 'Coll Dev' },
{ locCode: 'ediba',   locName: 'EDIBA Professional Reading Collection' },
{ locCode: 'eld',   locName: 'European Languages Division ELD' },
{ locCode: 'eldr',   locName: 'European Languages Division ELDR' },
{ locCode: 'hclcs',   locName: 'HCL Conservation Services' },
{ locCode: 'hclts',   locName: 'HCL TS' },
{ locCode: 'hdeld',   locName: 'European Languages Division (HD)' },
{ locCode: 'hdjud',   locName: 'Offsite Storage (Judaica) (HD)' },
{ locCode: 'hdmid',   locName: 'Middle Eastern Division (HD)' },
{ locCode: 'hdscp',   locName: 'Offsite Storage SCP (HD)' },
{ locCode: 'jud',   locName: 'Judaica Division' },
{ locCode: 'loker',   locName: 'Loker Reference Collection' },
{ locCode: 'midea',   locName: 'Middle Eastern Division' },
{ locCode: 'modgr',   locName: 'Modern Greek Division' },
{ locCode: 'net',   locName: 'Networked Resource' },
{ locCode: 'nmfl',   locName: 'Newspaper Microfilm Reading Room' },
{ locCode: 'perc',   locName: 'Widener Reading Room 150 Cage – staff only' },
{ locCode: 'perns',   locName: 'Widener Reading Room 150 Newspaper Stacks – Must request in-person' },
{ locCode: 'perr',   locName: 'Phillips Reading Room Periodicals' },
{ locCode: 'perrs',   locName: 'Widener Reading Room 150 Stacks – staff only' },
{ locCode: 'phone',   locName: 'Phone Chargers' },
{ locCode: 'prr',   locName: 'Phillips Reading Room' },
{ locCode: 'rdjud',   locName: 'Offsite Storage (Judaica) (RD)' },
{ locCode: 'rdscp',   locName: 'Offsite Storage SCP (RD)' },
{ locCode: 'resseq',   locName: 'Reserves Sequester' },
{ locCode: 'rm745',   locName: 'Widener Room 745 (WID Judaica)' },
{ locCode: 'roome',   locName: 'Widener Room E (Smyth)' },
{ locCode: 'roomg',   locName: 'Widener Room G (WID Assyriology)' },
{ locCode: 'roos',   locName: 'Roosevelt' },
{ locCode: 'slav',   locName: 'Slavic Division' },
{ locCode: 'tibet',   locName: 'Tibetan Collection' },
{ locCode: 'widhe',   locName: 'WID-LC Hebrew' },
{ locCode: 'widlc',   locName: 'WID-LC' },
{ locCode: 'widme',   locName: 'WID-LC Mid East' },
{ locCode: 'widph',   locName: 'WID-LC Phillips' },
{ locCode: 'widyi',   locName: 'WID-LC Yiddish' },
{ locCode: 'wsrr',   locName: 'West Stacks Reading Room' }
]
}
		];

		 var serviceLoc = {
            getliblocs: getliblocs
        	};

        return serviceLoc;

	   function getliblocs() {
            return liblocs;
        }

	}

})();