// marc place of publication codes
(function () {
  'use strict';

  angular.module('viewCustom')
  .factory('pubplaceService', pubplaceService);

	// # pubplace and xrefs 

	function pubplaceService() {

		var pubplaces = [
    			{ name: 'Afghanistan', code: 'af' },
			{ name: 'Alabama', code: 'alu' },
			{ name: 'Alaska', code: 'aku' },
			{ name: 'Albania', code: 'aa' },
			{ name: 'Alberta', code: 'abc' },
			{ name: 'Algeria', code: 'ae' },
			{ name: 'American Samoa', code: 'as' },
			{ name: 'Eastern Samoa --> use American Samoa', code: 'as' },
			{ name: 'Samoa, American --> use American Samoa', code: 'as' },
			{ name: 'Andorra', code: 'an' },
			{ name: 'Angola', code: 'ao' },
			{ name: 'Cabinda --> use Angola', code: 'ao' },
			{ name: 'Anguilla', code: 'am' },
			{ name: 'Saint Kitts-Nevis-Anguilla --> use Anguilla', code: 'am' },
			{ name: 'Sombrero Island --> use Anguilla', code: 'am' },
			{ name: 'Antarctica', code: 'ay' },
			{ name: 'Antigua and Barbuda', code: 'aq' },
			{ name: 'Antigua --> use Antigua and Barbuda', code: 'aq' },
			{ name: 'Barbuda --> use Antigua and Barbuda', code: 'aq' },
			{ name: 'Redonda --> use Antigua and Barbuda', code: 'aq' },
			{ name: 'Argentina', code: 'ag' },
			{ name: 'Arizona', code: 'azu' },
			{ name: 'Arkansas', code: 'aru' },
			{ name: 'Armenia (Republic)', code: 'ai' },
			{ name: 'Aruba', code: 'aw' },
			{ name: 'Australia', code: 'at' },
			{ name: 'Ashmore and Cartier Islands --> use Australia', code: 'at' },
			{ name: 'Macquarie Island --> use Australia', code: 'at' },
			{ name: 'Australian Capital Territory', code: 'aca' },
			{ name: 'Austria', code: 'au' },
			{ name: 'Azerbaijan', code: 'aj' },
			{ name: 'Bahamas', code: 'bf' },
			{ name: 'Bahrain', code: 'ba' },
			{ name: 'Bahrein --> use Bahrain', code: 'ba' },
			{ name: 'Bangladesh', code: 'bg' },
			{ name: 'East Pakistan --> use Bangladesh', code: 'bg' },
			{ name: 'Barbados', code: 'bb' },
			{ name: 'Belarus', code: 'bw' },
			{ name: 'Byelarus --> use Belarus', code: 'bw' },
			{ name: 'Belorussian S.S.R. --> use Belarus', code: 'bw' },
			{ name: 'Byeolorussian S.S.R. --> use Belarus', code: 'bw' },
			{ name: 'Belgium', code: 'be' },
			{ name: 'Belize', code: 'bh' },
			{ name: 'British Honduras --> use Belize', code: 'bh' },
			{ name: 'Benin', code: 'dm' },
			{ name: 'Dahomey --> use Benin', code: 'dm' },
			{ name: 'Bermuda Islands', code: 'bm' },
			{ name: 'Bhutan', code: 'bt' },
			{ name: 'Bolivia', code: 'bo' },
			{ name: 'Bosnia and Herzegovina', code: 'bn' },
			{ name: 'Bosnia and Hercegovina --> use Bosnia and Herzegovina', code: 'bn' },
			{ name: 'Hercegovina --> use Bosnia and Herzegovina', code: 'bn' },
			{ name: 'Herzegovina --> use Bosnia and Herzegovina', code: 'bn' },
			{ name: 'Botswana', code: 'bs' },
			{ name: 'Bechuanaland --> use Botswana', code: 'bs' },
			{ name: 'Bouvet Island', code: 'bv' },
			{ name: 'Brazil', code: 'bl' },
			{ name: 'Fernando de Noronha --> use Brazil', code: 'bl' },
			{ name: 'Ilha da Trindade --> use Brazil', code: 'bl' },
			{ name: 'Ilhas Martim Vaz --> use Brazil', code: 'bl' },
			{ name: 'Martim Vaz, Ilhas --> use Brazil', code: 'bl' },
			{ name: 'Penedos de São Pedro e São Paulo --> use Brazil', code: 'bl' },
			{ name: 'Rocas --> use Brazil', code: 'bl' },
			{ name: 'Trindade, Ilha da --> use Brazil', code: 'bl' },
			{ name: 'British Columbia', code: 'bcc' },
			{ name: 'British Indian Ocean Territory', code: 'bi' },
			{ name: 'Chagos Archipelago --> use British Indian Ocean Territory', code: 'bi' },
			{ name: 'Diego Garcia Island --> use British Indian Ocean Territory', code: 'bi' },
			{ name: 'British Virgin Islands', code: 'vb' },
			{ name: 'Anegada --> use British Virgin Islands', code: 'vb' },
			{ name: 'Colony of the Virgin Islands --> use British Virgin Islands', code: 'vb' },
			{ name: 'Jost Van Dyke --> use British Virgin Islands', code: 'vb' },
			{ name: 'Tortola --> use British Virgin Islands', code: 'vb' },
			{ name: 'Virgin Gorda --> use British Virgin Islands', code: 'vb' },
			{ name: 'Virgin Islands (British) --> use British Virgin Islands', code: 'vb' },
			{ name: 'Brunei', code: 'bx' },
			{ name: 'Bulgaria', code: 'bu' },
			{ name: 'Burkina Faso', code: 'uv' },
			{ name: 'Upper Volta --> use Burkina Faso', code: 'uv' },
			{ name: 'Burma', code: 'br' },
			{ name: 'Myanmar --> use Burma', code: 'br' },
			{ name: 'Burundi', code: 'bd' },
			{ name: 'California', code: 'cau' },
			{ name: 'Cambodia', code: 'cb' },
			{ name: 'Democratic Kampuchea --> use Cambodia', code: 'cb' },
			{ name: 'Kampuchea --> use Cambodia', code: 'cb' },
			{ name: 'Khmer Republic --> use Cambodia', code: 'cb' },
			{ name: 'Cameroon', code: 'cm' },
			{ name: 'British Cameroons --> use Cameroon', code: 'cm' },
			{ name: 'East Cameroon --> use Cameroon', code: 'cm' },
			{ name: 'French Cameroons --> use Cameroon', code: 'cm' },
			{ name: 'German Cameroons --> use Cameroon', code: 'cm' },
			{ name: 'Southern Cameroons --> use Cameroon', code: 'cm' },
			{ name: 'West Cameroon --> use Cameroon', code: 'cm' },
			{ name: 'Canada', code: 'xxc' },
			{ name: 'Cabo Verde', code: 'cv' },
			{ name: 'Boa Vista --> use Cabo Verde', code: 'cv' },
			{ name: 'Brava --> use Cabo Verde', code: 'cv' },
			{ name: 'Cape Verde --> use Cabo Verde', code: 'cv' },
			{ name: 'Fogo --> use Cabo Verde', code: 'cv' },
			{ name: 'Maio --> use Cabo Verde', code: 'cv' },
			{ name: 'Sal --> use Cabo Verde', code: 'cv' },
			{ name: 'Santo Antao --> use Cabo Verde', code: 'cv' },
			{ name: 'São Nicolau --> use Cabo Verde', code: 'cv' },
			{ name: 'São Tiago --> use Cabo Verde', code: 'cv' },
			{ name: 'São Vicente --> use Cabo Verde', code: 'cv' },
			{ name: 'Caribbean Netherlands', code: 'ca' },
			{ name: 'BES Islands --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Bonaire --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Bonaire (Netherlands Antilles) --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Bonaire, Saint Eustatius, and Saba --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Dutch Caribbean --> use Caribbean Netherlands', code: 'ca' },
			// { name: 'Netherlands Antilles --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Saba --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Saba (Netherlands Antilles) --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Saint Eustatius --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Sint Eustatius --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Sint Eustatius (Netherlands Antilles) --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Statia (Netherlands Antilles) --> use Caribbean Netherlands', code: 'ca' },
			{ name: 'Cayman Islands', code: 'cj' },
			{ name: 'Cayman Brac Island --> use Cayman Islands', code: 'cj' },
			{ name: 'Grand Cayman Island --> use Cayman Islands', code: 'cj' },
			{ name: 'Little Cayman Island --> use Cayman Islands', code: 'cj' },
			{ name: 'Central African Republic', code: 'cx' },
			{ name: 'Central African Empire --> use Central African Republic', code: 'cx' },
			{ name: 'Ubangi-Shari --> use Central African Republic', code: 'cx' },
			{ name: 'Chad', code: 'cd' },
			{ name: 'Chile', code: 'cl' },
			{ name: 'Easter Island --> use Chile', code: 'cl' },
			{ name: 'Isla de Pasqua --> use Chile', code: 'cl' },
			{ name: 'Isla Sala y Gómez --> use Chile', code: 'cl' },
			{ name: 'Islas Juan Fernández --> use Chile', code: 'cl' },
			{ name: 'Juan Fernández, Islas --> use Chile', code: 'cl' },
			{ name: 'Pasqua, Isla de --> use Chile', code: 'cl' },
			{ name: 'Sala y Gómez, Isla --> use Chile', code: 'cl' },
			{ name: 'San Félix --> use Chile', code: 'cl' },
			{ name: 'China', code: 'cc' },
			{ name: 'Hainan Island --> use China', code: 'cc' },
			{ name: 'Hong Kong --> use China', code: 'cc' },
			{ name: 'Inner Mongolia --> use China', code: 'cc' },
			{ name: 'Kowloon --> use China', code: 'cc' },
			{ name: 'Macao --> use China', code: 'cc' },
			{ name: 'Macau --> use China', code: 'cc' },
			{ name: 'Manchuria --> use China', code: 'cc' },
			{ name: 'Sinkiang --> use China', code: 'cc' },
			{ name: 'New Territories --> use China', code: 'cc' },
			{ name: 'Taipa --> use China', code: 'cc' },
			{ name: 'Tibet --> use China', code: 'cc' },
			{ name: 'China (Republic : 1949- )', code: 'ch' },
			{ name: 'Formosa Island --> use China (Republic : 1949- )', code: 'ch' },
			{ name: 'Nationalist China --> use China (Republic : 1949- )', code: 'ch' },
			{ name: 'P\'eng-hu Island --> use China (Republic : 1949- )', code: 'ch' },
			{ name: 'Pescadores Islands --> use China (Republic : 1949- )', code: 'ch' },
			{ name: 'Taiwan Island --> use China (Republic : 1949- )', code: 'ch' },
			{ name: 'Christmas Island (Indian Ocean)', code: 'xa' },
			{ name: 'Cocos (Keeling) Islands', code: 'xb' },
			{ name: 'Keeling Islands --> use Cocos (Keeling) Islands', code: 'xb' },
			{ name: 'Colombia', code: 'ck' },
			{ name: 'Isla de Malpelo --> use Colombia', code: 'ck' },
			{ name: 'Malpelo, Isla de --> use Colombia', code: 'ck' },
			{ name: 'San Andrés y Providencia --> use Colombia', code: 'ck' },
			{ name: 'Serrana Bank --> use Colombia', code: 'ck' },
			{ name: 'Serranilla Bank --> use Colombia', code: 'ck' },
			{ name: 'Colorado', code: 'cou' },
			{ name: 'Comoros', code: 'cq' },
			{ name: 'Anjouan Island --> use Comoros', code: 'cq' },
			{ name: 'Comores --> use Comoros', code: 'cq' },
			{ name: 'Grande Comore Island --> use Comoros', code: 'cq' },
			{ name: 'Moheli Island --> use Comoros', code: 'cq' },
			{ name: 'Congo (Brazzaville)', code: 'cf' },
			{ name: 'Middle Congo --> use Congo (Brazzaville)', code: 'cf' },
			{ name: 'Congo (Democratic Republic)', code: 'cg' },
			{ name: 'Belgian Congo --> use Congo (Democratic Republic)', code: 'cg' },
			{ name: 'Congo (Kinshasa) --> use Congo (Democratic Republic)', code: 'cg' },
			{ name: 'Democratic Republic of the Congo --> use Congo (Democratic Republic)', code: 'cg' },
			{ name: 'Zaire --> use Congo (Democratic Republic)', code: 'cg' },
			{ name: 'Connecticut ', code: 'ctu' },
			{ name: 'Cook Islands', code: 'cw' },
			{ name: 'Danger Atoll --> use Cook Islands', code: 'cw' },
			{ name: 'Manihiki Atoll --> use Cook Islands', code: 'cw' },
			{ name: 'Penrhyn Atoll --> use Cook Islands', code: 'cw' },
			{ name: 'Rakahanga Atoll --> use Cook Islands', code: 'cw' },
			{ name: 'Coral Sea Islands Territory', code: 'xga' },
			{ name: 'Costa Rica', code: 'cr' },
			{ name: 'Cocos Island --> use Costa Rica', code: 'cr' },
			{ name: 'Côte d\'Ivoire', code: 'iv' },
			{ name: 'Ivory Coast --> use Côte d\'Ivoire', code: 'iv' },
			{ name: 'Croatia', code: 'ci' },
			{ name: 'Cuba', code: 'cu' },
			{ name: 'Isle of Pines (Caribbean) --> use Cuba', code: 'cu' },
			{ name: 'Pines, Isle of (Caribbean) --> use Cuba', code: 'cu' },
			{ name: 'Curaçao', code: 'co' },
			{ name: 'Curaçao (Netherlands Antilles) --> use Curaçao', code: 'co' },
			// { name: 'Netherlands Antilles --> use Curaçao', code: 'co' },
			{ name: 'Cyprus', code: 'cy' },
			{ name: 'Czech Republic', code: 'xr' },
			// { name: 'Czechoslovakia --> use Czech Republic', code: 'xr' },
			{ name: 'Delaware', code: 'deu' },
			{ name: 'Denmark', code: 'dk' },
			{ name: 'Bornholm Island --> use Denmark', code: 'dk' },
			{ name: 'District of Columbia (Washington, D.C.)', code: 'dcu' },
			{ name: 'Djibouti', code: 'ft' },
			{ name: 'Afars --> use Djibouti', code: 'ft' },
			{ name: 'French Somaliland --> use Djibouti', code: 'ft' },
			{ name: 'French Territory of the Afars and Issas --> use Djibouti', code: 'ft' },
			{ name: 'Issas --> use Djibouti', code: 'ft' },
			{ name: 'Dominica', code: 'dq' },
			{ name: 'Dominican Republic', code: 'dr' },
			{ name: 'Ecuador', code: 'ec' },
			{ name: 'Archipiélago de Colón --> use Ecuador', code: 'ec' },
			{ name: 'Colón, Archipiélago de --> use Ecuador', code: 'ec' },
			{ name: 'Galapagos Islands --> use Ecuador', code: 'ec' },
			{ name: 'Egypt', code: 'ua' },
			{ name: 'Arab Republic of Egypt --> use Egypt', code: 'ua' },
			{ name: 'United Arab Republic --> use Egypt', code: 'ua' },
			{ name: 'El Salvador', code: 'es' },
			{ name: 'Salvador --> use El Salvador', code: 'es' },
			{ name: 'England', code: 'enk' },
			{ name: 'Equatorial Guinea', code: 'eg' },
			{ name: 'Annobón --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Bioko --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Corisco Island --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Elobey, Great --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Elobey, Small --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Fernando Po Island --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Macias Nguema Biyogo --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Pagalu --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Rio Muni --> use Equatorial Guinea', code: 'eg' },
			{ name: 'Eritrea', code: 'ea' },
			{ name: 'Estonia', code: 'er' },
			{ name: 'Eswatini', code: 'sq' },
			{ name: 'Swaziland --> use Eswatini', code: 'sq' },
			{ name: 'Ethiopia', code: 'et' },
			{ name: 'Falkland Islands', code: 'fk' },
			{ name: 'East Falkland Island --> use Falkland Islands', code: 'fk' },
			{ name: 'Islas Malvinas --> use Falkland Islands', code: 'fk' },
			{ name: 'Malvinas, Islas --> use Falkland Islands', code: 'fk' },
			{ name: 'West Falkland Island --> use Falkland Islands', code: 'fk' },
			{ name: 'Faroe Islands', code: 'fa' },
			{ name: 'Færoe Islands --> use Faroe Islands', code: 'fa' },
			{ name: 'Fiji', code: 'fj' },
			{ name: 'Rotuma Island --> use Fiji', code: 'fj' },
			{ name: 'Vanua Levu Island --> use Fiji', code: 'fj' },
			{ name: 'Viti Levu Island --> use Fiji', code: 'fj' },
			{ name: 'Finland', code: 'fi' },
			{ name: 'Ahvenanmaa --> use Finland', code: 'fi' },
			{ name: 'Åland Islands --> use Finland', code: 'fi' },
			{ name: 'Florida', code: 'flu' },
			{ name: 'France', code: 'fr' },
			{ name: 'Corsica --> use France', code: 'fr' },
			{ name: 'French Guiana', code: 'fg' },
			{ name: 'Guiana, French --> use French Guiana', code: 'fg' },
			{ name: 'French Polynesia', code: 'fp' },
			{ name: 'Austral Islands --> use French Polynesia', code: 'fp' },
			{ name: 'Clipperton Island --> use French Polynesia', code: 'fp' },
			{ name: 'Gambier Islands --> use French Polynesia', code: 'fp' },
			{ name: 'Iles Australes --> use French Polynesia', code: 'fp' },
			{ name: 'Iles du Vent --> use French Polynesia', code: 'fp' },
			{ name: 'Iles Sous le Vent --> use French Polynesia', code: 'fp' },
			{ name: 'Marquesas Islands --> use French Polynesia', code: 'fp' },
			{ name: 'Polynesia, French --> use French Polynesia', code: 'fp' },
			{ name: 'Society Islands --> use French Polynesia', code: 'fp' },
			{ name: 'Sous le Vent, Iles --> use French Polynesia', code: 'fp' },
			{ name: 'Tahiti --> use French Polynesia', code: 'fp' },
			{ name: 'Tuamotu Archipelago --> use French Polynesia', code: 'fp' },
			{ name: 'Vent, Iles du --> use French Polynesia', code: 'fp' },
			{ name: 'Gabon', code: 'go' },
			{ name: 'Gambia', code: 'gm' },
			{ name: 'Gaza Strip', code: 'gz' },
			{ name: 'Georgia', code: 'gau' },
			{ name: 'Georgia (Republic)', code: 'gs' },
			{ name: 'Germany', code: 'gw' },
			{ name: 'Berlin, East --> use Germany', code: 'gw' },
			{ name: 'Berlin, West --> use Germany', code: 'gw' },
			{ name: 'East Berlin --> use Germany', code: 'gw' },
			{ name: 'Germany (East) --> use Germany', code: 'gw' },
			{ name: 'Germany (West) --> use Germany', code: 'gw' },
			{ name: 'Germany, Democratic Republic of --> use Germany', code: 'gw' },
			{ name: 'Germany, Federal Republic of --> use Germany', code: 'gw' },
			{ name: 'West Berlin --> use Germany', code: 'gw' },
			{ name: 'Ghana', code: 'gh' },
			{ name: 'Ashanti --> use Ghana', code: 'gh' },
			{ name: 'Gold Coast --> use Ghana', code: 'gh' },
			{ name: 'Northern Territories --> use Ghana', code: 'gh' },
			{ name: 'Togoland --> use Ghana', code: 'gh' },
			{ name: 'Gibraltar', code: 'gi' },
			{ name: 'Greece', code: 'gr' },
			{ name: 'Aegean Islands --> use Greece', code: 'gr' },
			{ name: 'Crete --> use Greece', code: 'gr' },
			{ name: 'Dodecanese --> use Greece', code: 'gr' },
			{ name: 'Ionian Islands --> use Greece', code: 'gr' },
			{ name: 'Mount Athos --> use Greece', code: 'gr' },
			{ name: 'Greenland', code: 'gl' },
			{ name: 'Grenada', code: 'gd' },
			{ name: 'Grenadine Islands, Southern --> use Grenada', code: 'gd' },
			{ name: 'Guadeloupe', code: 'gp' },
			{ name: 'Basse-Terre --> use Guadeloupe', code: 'gp' },
			{ name: 'Grande-Terre --> use Guadeloupe', code: 'gp' },
			{ name: 'Iles de la Petite Terre --> use Guadeloupe', code: 'gp' },
			{ name: 'Iles des Saintes --> use Guadeloupe', code: 'gp' },
			{ name: 'La Désirade --> use Guadeloupe', code: 'gp' },
			{ name: 'Marie-Galante --> use Guadeloupe', code: 'gp' },
			{ name: 'Petite Terre, Iles de --> use Guadeloupe', code: 'gp' },
			{ name: 'Saintes, Iles des --> use Guadeloupe', code: 'gp' },
			{ name: 'Guam', code: 'gu' },
			{ name: 'Guatemala', code: 'gt' },
			{ name: 'Guernsey', code: 'gg' },
			{ name: 'Alderney --> use Guernsey', code: 'gg' },
			{ name: 'Brechou --> use Guernsey', code: 'gg' },
			{ name: 'Brecqhou --> use Guernsey', code: 'gg' },
			{ name: 'Channel Islands --> use Guernsey', code: 'gg' },
			{ name: 'Guernsey Island --> use Guernsey', code: 'gg' },
			{ name: 'Herm --> use Guernsey', code: 'gg' },
			{ name: 'Herm Island --> use Guernsey', code: 'gg' },
			{ name: 'Jethou --> use Guernsey', code: 'gg' },
			{ name: 'Lihou --> use Guernsey', code: 'gg' },
			{ name: 'Sark --> use Guernsey', code: 'gg' },
			{ name: 'Sark Island --> use Guernsey', code: 'gg' },
			// { name: 'United Kingdom Misc. Islands --> use Guernsey', code: 'gg' },
			{ name: 'Guinea', code: 'gv' },
			{ name: 'French Guinea --> use Guinea', code: 'gv' },
			{ name: 'Guinea-Bissau', code: 'pg' },
			{ name: 'Arquipélago dos Bijagós --> use Guinea-Bissau', code: 'pg' },
			{ name: 'Bijagós, Arquipélago dos --> use Guinea-Bissau', code: 'pg' },
			{ name: 'Bissagos Islands --> use Guinea-Bissau', code: 'pg' },
			{ name: 'Guinea, Portuguese --> use Guinea-Bissau', code: 'pg' },
			{ name: 'Portuguese Guinea --> use Guinea-Bissau', code: 'pg' },
			{ name: 'Guyana', code: 'gy' },
			{ name: 'British Guiana --> use Guyana', code: 'gy' },
			{ name: 'Guiana, British --> use Guyana', code: 'gy' },
			{ name: 'Haiti', code: 'ht' },
			{ name: 'Hawaii', code: 'hiu' },
			{ name: 'Heard and McDonald Islands', code: 'hm' },
			{ name: 'Honduras', code: 'ho' },
			{ name: 'Swan Islands --> use Honduras', code: 'ho' },
			{ name: 'Hungary', code: 'hu' },
			{ name: 'Iceland', code: 'ic' },
			{ name: 'Idaho', code: 'idu' },
			{ name: 'Illinois', code: 'ilu' },
			{ name: 'India', code: 'ii' },
			{ name: 'Amindivi Islands --> use India', code: 'ii' },
			{ name: 'Andaman Islands --> use India', code: 'ii' },
			{ name: 'Daman --> use India', code: 'ii' },
			{ name: 'Diu --> use India', code: 'ii' },
			{ name: 'Goa --> use India', code: 'ii' },
			{ name: 'Laccadive Island --> use India', code: 'ii' },
			{ name: 'Minicoy Island --> use India', code: 'ii' },
			{ name: 'Nicobar Islands --> use India', code: 'ii' },
			{ name: 'Sikkim --> use India', code: 'ii' },
			{ name: 'Indiana', code: 'inu' },
			{ name: 'Indonesia', code: 'io' },
			{ name: 'Irian Barat --> use Indonesia', code: 'io' },
			{ name: 'Netherlands New Guinea --> use Indonesia', code: 'io' },
			{ name: 'West New Guinea --> use Indonesia', code: 'io' },
			{ name: 'Iowa', code: 'iau' },
			{ name: 'Iran', code: 'ir' },
			{ name: 'Iraq', code: 'iq' },
			{ name: 'Iraq-Saudi Arabia Neutral Zone', code: 'iy' },
			{ name: 'Ireland', code: 'ie' },
			{ name: 'Eire --> use Ireland', code: 'ie' },
			{ name: 'Isle of Man', code: 'im' },
			{ name: 'Calf of Man --> use Isle of Man', code: 'im' },
			// { name: 'United Kingdom Misc. Islands --> use Isle of Man', code: 'im' },
			{ name: 'Israel', code: 'is' },
			{ name: 'Israel-Jordan Demilitarized Zones --> use Israel', code: 'is' },
			{ name: 'Israel-Syria Demilitarized Zones --> use Israel', code: 'is' },
			{ name: 'Italy', code: 'it' },
			{ name: 'Pantelleria --> use Italy', code: 'it' },
			{ name: 'Sardinia --> use Italy', code: 'it' },
			{ name: 'Sicily --> use Italy', code: 'it' },
			{ name: 'Jamaica', code: 'jm' },
			{ name: 'Morant Cays --> use Jamaica', code: 'jm' },
			{ name: 'Pedro Cays --> use Jamaica', code: 'jm' },
			{ name: 'Japan', code: 'ja' },
			{ name: 'Bonin Islands --> use Japan', code: 'ja' },
			{ name: 'Daitojima --> use Japan', code: 'ja' },
			{ name: 'Marcus Island --> use Japan', code: 'ja' },
			{ name: 'Namposhoto (Northern) --> use Japan', code: 'ja' },
			{ name: 'Namposhoto (Southern) --> use Japan', code: 'ja' },
			{ name: 'Nishinoshima Island --> use Japan', code: 'ja' },
			{ name: 'Okinawa --> use Japan', code: 'ja' },
			{ name: 'Parece Vela Island --> use Japan', code: 'ja' },
			{ name: 'Ryukyu Islands, Northern --> use Japan', code: 'ja' },
			{ name: 'Ryukyu Islands, Southern --> use Japan', code: 'ja' },
			{ name: 'Torishima --> use Japan', code: 'ja' },
			{ name: 'Volcano Islands --> use Japan', code: 'ja' },
			{ name: 'Jersey', code: 'je' },
			{ name: 'Channel Islands --> use Jersey', code: 'je' },
			{ name: 'Jersey (Island) --> use Jersey', code: 'je' },
			// { name: 'United Kingdom Misc. Islands --> use Jersey', code: 'je' },
			{ name: 'Johnston Atoll', code: 'ji' },
			{ name: 'Sand Island --> use Johnston Atoll', code: 'ji' },
			{ name: 'Jordan', code: 'jo' },
			{ name: 'Kansas', code: 'ksu' },
			{ name: 'Kazakhstan', code: 'kz' },
			{ name: 'Kazakh S.S.R. --> use Kazakhstan', code: 'kz' },
			{ name: 'Kentucky', code: 'kyu' },
			{ name: 'Kenya', code: 'ke' },
			{ name: 'Kiribati', code: 'gb' },
			{ name: 'Banaba --> use Kiribati', code: 'gb' },
			{ name: 'Birnie Island --> use Kiribati', code: 'gb' },
			{ name: 'Canton Island --> use Kiribati', code: 'gb' },
			{ name: 'Caroline Island --> use Kiribati', code: 'gb' },
			{ name: 'Central and Southern Line Islands --> use Kiribati', code: 'gb' },
			{ name: 'Christmas Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Enderbury Island --> use Kiribati', code: 'gb' },
			{ name: 'Fanning Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Flint Island --> use Kiribati', code: 'gb' },
			{ name: 'Gardner Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Gilbert and Ellice Islands --> use Kiribati', code: 'gb' },
			{ name: 'Gilbert Islands --> use Kiribati', code: 'gb' },
			{ name: 'Hull Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Kiritimati --> use Kiribati', code: 'gb' },
			{ name: 'Line Islands (Southern) --> use Kiribati', code: 'gb' },
			{ name: 'Malden Island --> use Kiribati', code: 'gb' },
			{ name: 'Manra Atoll --> use Kiribati', code: 'gb' },
			{ name: 'McKean Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Nikomaroro Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Ocean Island --> use Kiribati', code: 'gb' },
			{ name: 'Orona Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Phoenix Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Phoenix Islands --> use Kiribati', code: 'gb' },
			{ name: 'Rawaki --> use Kiribati', code: 'gb' },
			{ name: 'Starbuck Island --> use Kiribati', code: 'gb' },
			{ name: 'Sydney Atoll --> use Kiribati', code: 'gb' },
			{ name: 'Tabuarean Island --> use Kiribati', code: 'gb' },
			{ name: 'Vostok Island --> use Kiribati', code: 'gb' },
			{ name: 'Washington Island --> use Kiribati', code: 'gb' },
			{ name: 'Korea (North)', code: 'kn' },
			{ name: 'Democratic People\'s Republic of Korea --> use Korea (North)', code: 'kn' },
			{ name: 'North Korea --> use Korea (North)', code: 'kn' },
			{ name: 'Korea (South)', code: 'ko' },
			{ name: 'Korea, Republic of --> use Korea (South)', code: 'ko' },
			{ name: 'South Korea --> use Korea (South)', code: 'ko' },
			{ name: 'Kosovo', code: 'kv' },
			{ name: 'Kuwait', code: 'ku' },
			{ name: 'Kyrgyzstan', code: 'kg' },
			{ name: 'Kirghiz S.S.R. --> use Kyrgyzstan', code: 'kg' },
			{ name: 'Kirghizia --> use Kyrgyzstan', code: 'kg' },
			{ name: 'Laos', code: 'ls' },
			{ name: 'Latvia', code: 'lv' },
			{ name: 'Lebanon', code: 'le' },
			{ name: 'Lesotho', code: 'lo' },
			{ name: 'Basutoland --> use Lesotho', code: 'lo' },
			{ name: 'Liberia', code: 'lb' },
			{ name: 'Libya', code: 'ly' },
			{ name: 'Liechtenstein', code: 'lh' },
			{ name: 'Lithuania', code: 'li' },
			{ name: 'Louisiana', code: 'lau' },
			{ name: 'Luxembourg', code: 'lu' },
			{ name: 'Madagascar', code: 'mg' },
			{ name: 'Malagasy Republic --> use Madagascar', code: 'mg' },
			{ name: 'Maine', code: 'meu' },
			{ name: 'Malawi', code: 'mw' },
			{ name: 'Nyasaland --> use Malawi', code: 'mw' },
			{ name: 'Malaysia', code: 'my' },
			{ name: 'Borneo, North --> use Malaysia', code: 'my' },
			{ name: 'Malaya --> use Malaysia', code: 'my' },
			{ name: 'North Borneo --> use Malaysia', code: 'my' },
			{ name: 'Sabah --> use Malaysia', code: 'my' },
			{ name: 'Sarawak --> use Malaysia', code: 'my' },
			{ name: 'Maldives', code: 'xc' },
			{ name: 'Maldive Islands --> use Maldives', code: 'xc' },
			{ name: 'Mali', code: 'ml' },
			{ name: 'French Sudan --> use Mali', code: 'ml' },
			{ name: 'Soudan --> use Mali', code: 'ml' },
			{ name: 'Sudan, French --> use Mali', code: 'ml' },
			{ name: 'Malta', code: 'mm' },
			{ name: 'Comino Island --> use Malta', code: 'mm' },
			{ name: 'Gozo Island --> use Malta', code: 'mm' },
			{ name: 'Manitoba', code: 'mbc' },
			{ name: 'Marshall Islands', code: 'xe' },
			{ name: 'Ailinglapalap Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Arno (Atoll) --> use Marshall Islands', code: 'xe' },
			{ name: 'Bikini (Atoll) --> use Marshall Islands', code: 'xe' },
			{ name: 'Ebon Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Eniwetok Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Jaluit Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Kili Island --> use Marshall Islands', code: 'xe' },
			{ name: 'Kwajalein Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Majuro Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Maloelap Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Mili Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Namorik Atoll --> use Marshall Islands', code: 'xe' },
			// { name: 'Pacific Islands (Trust Territory) --> use Marshall Islands', code: 'xe' },
			{ name: 'Ralik Chain --> use Marshall Islands', code: 'xe' },
			{ name: 'Ratak Chains --> use Marshall Islands', code: 'xe' },
			{ name: 'Rongelap Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Taongi Atoll --> use Marshall Islands', code: 'xe' },
			// { name: 'Trust Territory of the Pacific Islands --> use Marshall Islands', code: 'xe' },
			{ name: 'Ujelang Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Utirik Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Wotje Atoll --> use Marshall Islands', code: 'xe' },
			{ name: 'Martinique', code: 'mq' },
			{ name: 'Maryland', code: 'mdu' },
			{ name: 'Massachusetts', code: 'mau' },
			{ name: 'Mauritania', code: 'mu' },
			{ name: 'Mauritius', code: 'mf' },
			{ name: 'Agalega Islands --> use Mauritius', code: 'mf' },
			{ name: 'Cargados Carajos Shoals --> use Mauritius', code: 'mf' },
			{ name: 'Rodrigues Island --> use Mauritius', code: 'mf' },
			{ name: 'Saint Brandon --> use Mauritius', code: 'mf' },
			{ name: 'Mayotte', code: 'ot' },
			{ name: 'Mexico', code: 'mx' },
			{ name: 'Islas de Revillagigedo --> use Mexico', code: 'mx' },
			{ name: 'Revillagigedo, Islas de --> use Mexico', code: 'mx' },
			{ name: 'Michigan', code: 'miu' },
			{ name: 'Micronesia (Federated States)', code: 'fm' },
			{ name: 'Ascension Island (Micronesia) --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Eauripik Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Fais Island --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Faraulep Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Federated States of Micronesia --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Gaferut Island --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Hall Islands --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Ifalik Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Kapingamarangi Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Kosrae (Micronesia) --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Kusaie (Micronesia) --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Mortlock Islands --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Namonuito Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Ngatik Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Ngulu Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Nukuoru Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Oroluk Atoll --> use Micronesia (Federated States)', code: 'fm' },
			// { name: 'Pacific Islands (Trust Territory) --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Pingelap Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Pohnpei --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Ponape (Micronesia) --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Pulap Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Pulusak Island --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Puluwat Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Satawal Island --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Senyavin Islands --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Truk (Micronesia) --> use Micronesia (Federated States)', code: 'fm' },
			// { name: 'Trust Territory of the Pacific Islands --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Ulithi Islands --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'West Fayu Atoll --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Woleai Atolls --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Yap (Micronesia) --> use Micronesia (Federated States)', code: 'fm' },
			{ name: 'Midway Islands', code: 'xf' },
			{ name: 'Minnesota', code: 'mnu' },
			{ name: 'Mississippi', code: 'msu' },
			{ name: 'Missouri', code: 'mou' },
			{ name: 'Moldova', code: 'mv' },
			{ name: 'Moldavian S.S.R. --> use Moldova', code: 'mv' },
			{ name: 'Monaco', code: 'mc' },
			{ name: 'Mongolia', code: 'mp' },
			{ name: 'Mongolian People\'s Republic --> use Mongolia', code: 'mp' },
			{ name: 'Outer Mongolia --> use Mongolia', code: 'mp' },
			{ name: 'Montana', code: 'mtu' },
			{ name: 'Montenegro', code: 'mo' },
			{ name: 'Yugoslavia --> use Montenegro', code: 'mo' },
			{ name: 'Montserrat', code: 'mj' },
			{ name: 'Morocco', code: 'mr' },
			{ name: 'French Morocco --> use Morocco', code: 'mr' },
			{ name: 'Ifni --> use Morocco', code: 'mr' },
			{ name: 'Spanish Morocco --> use Morocco', code: 'mr' },
			{ name: 'Tangier Zone --> use Morocco', code: 'mr' },
			{ name: 'Zona Sur del Protectorado de Marruecos --> use Morocco', code: 'mr' },
			{ name: 'Mozambique', code: 'mz' },
			{ name: 'Namibia', code: 'sx' },
			{ name: 'South-West Africa --> use Namibia', code: 'sx' },
			{ name: 'Nauru', code: 'nu' },
			{ name: 'Nebraska', code: 'nbu' },
			{ name: 'Nepal', code: 'np' },
			{ name: 'Netherlands', code: 'ne' },
			{ name: 'Holland --> use Netherlands', code: 'ne' },
			{ name: 'Nevada', code: 'nvu' },
			{ name: 'New Brunswick', code: 'nkc' },
			{ name: 'New Caledonia', code: 'nl' },
			{ name: 'Belep Islands --> use New Caledonia', code: 'nl' },
			{ name: 'Chesterfield, Iles --> use New Caledonia', code: 'nl' },
			{ name: 'Huon, Ile --> use New Caledonia', code: 'nl' },
			{ name: 'Ile des Pins --> use New Caledonia', code: 'nl' },
			{ name: 'Ile Huon --> use New Caledonia', code: 'nl' },
			{ name: 'Ile Uvea (New Caledonia) --> use New Caledonia', code: 'nl' },
			{ name: 'Ile Walpole --> use New Caledonia', code: 'nl' },
			{ name: 'Iles Belep --> use New Caledonia', code: 'nl' },
			{ name: 'Iles Chesterfield --> use New Caledonia', code: 'nl' },
			{ name: 'Isle of Pines (Pacific Ocean) --> use New Caledonia', code: 'nl' },
			{ name: 'Loyalty Islands --> use New Caledonia', code: 'nl' },
			{ name: 'Pines, Isle of (Pacific Ocean) --> use New Caledonia', code: 'nl' },
			{ name: 'Pins, Ile des --> use New Caledonia', code: 'nl' },
			{ name: 'Uvea (New Caledonia) --> use New Caledonia', code: 'nl' },
			{ name: 'Walpole, Ile --> use New Caledonia', code: 'nl' },
			{ name: 'New Hampshire', code: 'nhu' },
			{ name: 'New Jersey', code: 'nju' },
			{ name: 'New Mexico', code: 'nmu' },
			{ name: 'New South Wales', code: 'xna' },
			{ name: 'New York (State)', code: 'nyu' },
			{ name: 'New Zealand', code: 'nz' },
			{ name: 'Chatham Islands --> use New Zealand', code: 'nz' },
			{ name: 'Kermadec Islands --> use New Zealand', code: 'nz' },
			{ name: 'North Island --> use New Zealand', code: 'nz' },
			{ name: 'South Island --> use New Zealand', code: 'nz' },
			{ name: 'Stewart Island --> use New Zealand', code: 'nz' },
			{ name: 'Newfoundland and Labrador', code: 'nfc' },
			{ name: 'Labrador --> use Newfoundland and Labrador', code: 'nfc' },
			{ name: 'Newfoundland --> use Newfoundland and Labrador', code: 'nfc' },
			{ name: 'Nicaragua', code: 'nq' },
			{ name: 'Corn Islands --> use Nicaragua', code: 'nq' },
			{ name: 'Niger', code: 'ng' },
			{ name: 'Nigeria', code: 'nr' },
			{ name: 'British Cameroons, Northern --> use Nigeria', code: 'nr' },
			{ name: 'Niue', code: 'xh' },
			{ name: 'No place, unknown, or undetermined', code: 'xx' },
			{ name: 'Norfolk Island ', code: 'nx' },
			{ name: 'North Carolina', code: 'ncu' },
			{ name: 'North Dakota', code: 'ndu' },
			{ name: 'North Macedonia', code: 'xn' },
			{ name: 'Macedonia (Republic) --> use North Macedonia', code: 'xn' },
			{ name: 'Northern Ireland', code: 'nik' },
			{ name: 'Ireland, Northern --> use Northern Ireland', code: 'nik' },
			{ name: 'Northern Mariana Islands', code: 'nw' },
			{ name: 'Agrihan Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Aguijan Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Alamagan Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Anatahan Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Asuncion Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Farallon de Medinilla Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Farallon de Pajaros Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Guguan Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Mariana Islands --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Maug Islands --> use Northern Mariana Islands', code: 'nw' },
			// { name: 'Pacific Islands (Trust Territory) --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Pagan Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Rota Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Saipan Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Sarigan Island --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Tinian Island --> use Northern Mariana Islands', code: 'nw' },
			// { name: 'Trust Territory of the Pacific Islands --> use Northern Mariana Islands', code: 'nw' },
			{ name: 'Northern Territory', code: 'xoa' },
			{ name: 'Northwest Territories', code: 'ntc' },
			{ name: 'Norway', code: 'no' },
			{ name: 'Bear Island --> use Norway', code: 'no' },
			{ name: 'Jan Mayen --> use Norway', code: 'no' },
			{ name: 'Spitsbergen --> use Norway', code: 'no' },
			{ name: 'Svalbard (Norway) --> use Norway', code: 'no' },
			{ name: 'Nova Scotia', code: 'nsc' },
			{ name: 'Nunavut', code: 'nuc' },
			{ name: 'Ohio', code: 'ohu' },
			{ name: 'Oklahoma', code: 'oku' },
			{ name: 'Oman', code: 'mk' },
			{ name: 'Kuria Muria Islands --> use Oman', code: 'mk' },
			{ name: 'Muscat and Oman --> use Oman', code: 'mk' },
			{ name: 'Ontario', code: 'onc' },
			{ name: 'Oregon', code: 'oru' },
			{ name: 'Pakistan', code: 'pk' },
			{ name: 'Gwadar --> use Pakistan', code: 'pk' },
			{ name: 'West Pakistan --> use Pakistan', code: 'pk' },
			{ name: 'Palau', code: 'pw' },
			{ name: 'Angaur Island --> use Palau', code: 'pw' },
			{ name: 'Babelthuap Island --> use Palau', code: 'pw' },
			{ name: 'Belau --> use Palau', code: 'pw' },
			{ name: 'Helen Island --> use Palau', code: 'pw' },
			{ name: 'Merir Island --> use Palau', code: 'pw' },
			// { name: 'Pacific Islands (Trust Territory) --> use Palau', code: 'pw' },
			{ name: 'Peleliu Island --> use Palau', code: 'pw' },
			{ name: 'Pelew --> use Palau', code: 'pw' },
			{ name: 'Pulo Anna Island --> use Palau', code: 'pw' },
			{ name: 'Sonsoral Islands --> use Palau', code: 'pw' },
			{ name: 'Tobi Island --> use Palau', code: 'pw' },
			// { name: 'Trust Territory of the Pacific Islands --> use Palau', code: 'pw' },
			{ name: 'Panama', code: 'pn' },
			{ name: 'Canal Zone --> use Panama', code: 'pn' },
			{ name: 'Papua New Guinea', code: 'pp' },
			{ name: 'Admiralty Islands --> use Papua New Guinea', code: 'pp' },
			{ name: 'Bismarck Archipelago --> use Papua New Guinea', code: 'pp' },
			{ name: 'D\'Entrecasteaux Islands --> use Papua New Guinea', code: 'pp' },
			{ name: 'Louisiada Archipelago --> use Papua New Guinea', code: 'pp' },
			{ name: 'New Britain Island --> use Papua New Guinea', code: 'pp' },
			{ name: 'New Guinea --> use Papua New Guinea', code: 'pp' },
			{ name: 'New Ireland Island --> use Papua New Guinea', code: 'pp' },
			{ name: 'North East New Guinea --> use Papua New Guinea', code: 'pp' },
			{ name: 'Solomon Islands, Northern --> use Papua New Guinea', code: 'pp' },
			{ name: 'Trobriand Islands --> use Papua New Guinea', code: 'pp' },
			{ name: 'Woodlark Island --> use Papua New Guinea', code: 'pp' },
			{ name: 'Paracel Islands]', code: 'pf' },
			{ name: 'Paraguay', code: 'py' },
			{ name: 'Pennsylvania', code: 'pau' },
			{ name: 'Peru', code: 'pe' },
			{ name: 'Philippines', code: 'ph' },
			{ name: 'Pitcairn Island', code: 'pc' },
			{ name: 'Ducie Atoll --> use Pitcairn Island', code: 'pc' },
			{ name: 'Henderson Island --> use Pitcairn Island', code: 'pc' },
			{ name: 'Oeno Atoll --> use Pitcairn Island', code: 'pc' },
			{ name: 'Poland', code: 'pl' },
			{ name: 'Portugal', code: 'po' },
			{ name: 'Azores --> use Portugal', code: 'po' },
			{ name: 'Madeira Island --> use Portugal', code: 'po' },
			{ name: 'Prince Edward Island', code: 'pic' },
			{ name: 'Puerto Rico', code: 'pr' },
			{ name: 'Qatar', code: 'qa' },
			{ name: 'Québec (Province)', code: 'quc' },
			{ name: 'Queensland', code: 'qea' },
			{ name: 'Réunion', code: 're' },
			{ name: 'Bassas da India --> use Réunion', code: 're' },
			{ name: 'Europa, Ile --> use Réunion', code: 're' },
			{ name: 'Glorieuses, Iles --> use Réunion', code: 're' },
			{ name: 'Ile Europa --> use Réunion', code: 're' },
			{ name: 'Ile Juan de Nova --> use Réunion', code: 're' },
			{ name: 'Ile Tromelin --> use Réunion', code: 're' },
			{ name: 'Iles Glorieuses --> use Réunion', code: 're' },
			{ name: 'Juan de Nova, Ile --> use Réunion', code: 're' },
			{ name: 'Tromelin, Ile --> use Réunion', code: 're' },
			{ name: 'Rhode Island', code: 'riu' },
			{ name: 'Romania', code: 'rm' },
			{ name: 'Rumania --> use Romania', code: 'rm' },
			{ name: 'Russia (Federation)', code: 'ru' },
			{ name: 'Franz Josef Land --> use Russia (Federation)', code: 'ru' },
			{ name: 'Habomai Islands --> use Russia (Federation)', code: 'ru' },
			{ name: 'Kuril Islands (Southern) --> use Russia (Federation)', code: 'ru' },
			{ name: 'New Siberian Islands --> use Russia (Federation)', code: 'ru' },
			{ name: 'Novaya Zemlya --> use Russia (Federation)', code: 'ru' },
			{ name: 'Russian S.F.S.R. --> use Russia (Federation)', code: 'ru' },
			{ name: 'Sakhalin (Southern) --> use Russia (Federation)', code: 'ru' },
			{ name: 'Severnaya Zemlya --> use Russia (Federation)', code: 'ru' },
			{ name: 'Soviet Union --> use Russia (Federation)', code: 'ru' },
			{ name: 'Wrangel Island --> use Russia (Federation)', code: 'ru' },
			{ name: 'Rwanda', code: 'rw' },
			{ name: 'Saint-Barthélemy', code: 'sc' },
			{ name: 'Ile Saint-Barthélemy --> use Saint-Barthélemy', code: 'sc' },
			{ name: 'Saint Bartholomew --> use Saint-Barthélemy', code: 'sc' },
			{ name: 'Saint Barts --> use Saint-Barthélemy', code: 'sc' },
			{ name: 'St. Barthélemy --> use Saint-Barthélemy', code: 'sc' },
			{ name: 'Saint Helena', code: 'xj' },
			{ name: 'Ascension Island (Atlantic Ocean) --> use Saint Helena', code: 'xj' },
			{ name: 'Gough Island --> use Saint Helena', code: 'xj' },
			{ name: 'Inaccessible Island --> use Saint Helena', code: 'xj' },
			{ name: 'Nightingale Island --> use Saint Helena', code: 'xj' },
			{ name: 'Tristan da Cunha Island --> use Saint Helena', code: 'xj' },
			{ name: 'Saint Kitts-Nevis', code: 'xd' },
			{ name: 'Saint Christopher --> use Saint Kitts-Nevis', code: 'xd' },
			{ name: 'Saint Kitts-Nevis-Anguilla --> use Saint Kitts-Nevis', code: 'xd' },
			{ name: 'St. Christopher --> use Saint Kitts-Nevis', code: 'xd' },
			{ name: 'Saint Lucia', code: 'xk' },
			{ name: 'Saint-Martin', code: 'st' },
			{ name: 'Collectivity of Saint Martin --> use Saint-Martin', code: 'st' },
			{ name: 'Saint-Martin (Collectivity) --> use Saint-Martin', code: 'st' },
			{ name: 'Saint-Martin (France: Collectivity) --> use Saint-Martin', code: 'st' },
			{ name: 'Saint Martin, Northern --> use Saint-Martin', code: 'st' },
			{ name: 'Saint Pierre and Miquelon', code: 'xl' },
			{ name: 'Miquelon --> use Saint Pierre and Miquelon', code: 'xl' },
			{ name: 'Saint Vincent and the Grenadines', code: 'xm' },
			{ name: 'Grenadine Islands, Northern --> use Saint Vincent and the Grenadines', code: 'xm' },
			{ name: 'Saint Vincent --> use Saint Vincent and the Grenadines', code: 'xm' },
			{ name: 'Samoa', code: 'ws' },
			{ name: 'Samoa i Sisifo --> use Samoa', code: 'ws' },
			{ name: 'Samoa, Western --> use Samoa', code: 'ws' },
			{ name: 'Savai\'i --> use Samoa', code: 'ws' },
			{ name: 'Upolu --> use Samoa', code: 'ws' },
			{ name: 'Western Samoa --> use Samoa', code: 'ws' },
			{ name: 'San Marino', code: 'sm' },
			{ name: 'Sao Tome and Principe', code: 'sf' },
			{ name: 'Saskatchewan', code: 'snc' },
			{ name: 'Saudi Arabia', code: 'su' },
			{ name: 'Scotland', code: 'stk' },
			{ name: 'Orkney Islands --> use Scotland', code: 'stk' },
			{ name: 'Shetland Islands --> use Scotland', code: 'stk' },
			// { name: 'United Kingdom Misc. Islands --> use Scotland', code: 'stk' },
			{ name: 'Senegal', code: 'sg' },
			{ name: 'Serbia', code: 'rb' },
			{ name: 'Yugoslavia --> use Serbia', code: 'rb' },
			{ name: 'Seychelles', code: 'se' },
			{ name: 'Aldabra Islands --> use Seychelles', code: 'se' },
			{ name: 'Alphonse Island --> use Seychelles', code: 'se' },
			{ name: 'Amirante Isles --> use Seychelles', code: 'se' },
			{ name: 'Bijoutier Island --> use Seychelles', code: 'se' },
			{ name: 'Cosmoledo Islands --> use Seychelles', code: 'se' },
			{ name: 'Desroches, Ile --> use Seychelles', code: 'se' },
			{ name: 'Farquhar Atoll --> use Seychelles', code: 'se' },
			{ name: 'François Island --> use Seychelles', code: 'se' },
			{ name: 'Ile Desroches --> use Seychelles', code: 'se' },
			{ name: 'Saint Francois Island --> use Seychelles', code: 'se' },
			{ name: 'Saint Pierre Islet --> use Seychelles', code: 'se' },
			{ name: 'Sierra Leone', code: 'sl' },
			{ name: 'Singapore', code: 'si' },
			{ name: 'Sint Maarten', code: 'sn' },
			// { name: 'Netherlands Antilles --> use Sint Maarten', code: 'sn' },
			{ name: 'Saint Martin, Southern --> use Sint Maarten', code: 'sn' },
			{ name: 'Sint Maarten (Netherlands Antilles) --> use Sint Maarten', code: 'sn' },
			{ name: 'Slovakia', code: 'xo' },
			// { name: 'Czechoslovakia --> use Slovakia', code: 'xo' },
			{ name: 'Slovak Socialist Republic --> use Slovakia', code: 'xo' },
			{ name: 'Slovenia', code: 'xv' },
			{ name: 'Solomon Islands', code: 'bp' },
			{ name: 'British Solomon Islands --> use Solomon Islands', code: 'bp' },
			{ name: 'Choiseul --> use Solomon Islands', code: 'bp' },
			{ name: 'Guadalcanal --> use Solomon Islands', code: 'bp' },
			{ name: 'Malaita --> use Solomon Islands', code: 'bp' },
			{ name: 'San Cristóbal --> use Solomon Islands', code: 'bp' },
			{ name: 'Santa Isabel --> use Solomon Islands', code: 'bp' },
			{ name: 'Solomon Islands Protectorate --> use Solomon Islands', code: 'bp' },
			{ name: 'Somalia', code: 'so' },
			{ name: 'Somali Republic --> use Somalia', code: 'so' },
			{ name: 'South Africa', code: 'sa' },
			{ name: 'Bophuthatswana --> use South Africa', code: 'sa' },
			{ name: 'Ciskei --> use South Africa', code: 'sa' },
			{ name: 'Lebowa --> use South Africa', code: 'sa' },
			{ name: 'Machangana --> use South Africa', code: 'sa' },
			{ name: 'Marion Island --> use South Africa', code: 'sa' },
			{ name: 'Prince Edward Islands --> use South Africa', code: 'sa' },
			{ name: 'South Sotho --> use South Africa', code: 'sa' },
			{ name: 'Transkei --> use South Africa', code: 'sa' },
			{ name: 'Tswana --> use South Africa', code: 'sa' },
			{ name: 'Venda --> use South Africa', code: 'sa' },
			{ name: 'Walvis Bay Enclave --> use South Africa', code: 'sa' },
			{ name: 'Zulu --> use South Africa', code: 'sa' },
			{ name: 'South Australia', code: 'xra' },
			{ name: 'South Carolina', code: 'scu' },
			{ name: 'South Dakota', code: 'sdu' },
			{ name: 'South Georgia and the South Sandwich Islands', code: 'xs' },
			{ name: 'South Georgia Island --> use South Georgia and the South Sandwich Islands', code: 'xs' },
			{ name: 'South Sandwich Islands --> use South Georgia and the South Sandwich Islands', code: 'xs' },
			{ name: 'South Sudan', code: 'sd' },
			{ name: 'Sudan, South --> use South Sudan', code: 'sd' },
			{ name: 'Spain', code: 'sp' },
			{ name: 'Balearic Islands --> use Spain', code: 'sp' },
			{ name: 'Canary Islands --> use Spain', code: 'sp' },
			{ name: 'Spanish North Africa', code: 'sh' },
			{ name: 'Ceuta --> use Spanish North Africa', code: 'sh' },
			{ name: 'Chafarinas, Islas --> use Spanish North Africa', code: 'sh' },
			{ name: 'Islas Chafarinas --> use Spanish North Africa', code: 'sh' },
			{ name: 'Melilla --> use Spanish North Africa', code: 'sh' },
			{ name: 'Peñón de Alhucemas --> use Spanish North Africa', code: 'sh' },
			{ name: 'Peñón de Vélez de la Gomera --> use Spanish North Africa', code: 'sh' },
			{ name: 'Plazas de Soberania --> use Spanish North Africa', code: 'sh' },
			{ name: 'Spanish Territories in Northern Morocco --> use Spanish North Africa', code: 'sh' },
			{ name: 'Spratly Island', code: 'xp' },
			{ name: 'Sri Lanka', code: 'ce' },
			{ name: 'Ceylon --> use Sri Lanka', code: 'ce' },
			{ name: 'Sudan', code: 'sj' },
			{ name: 'Surinam', code: 'sr' },
			{ name: 'Dutch Guiana --> use Surinam', code: 'sr' },
			{ name: 'Guiana, Dutch --> use Surinam', code: 'sr' },
			{ name: 'Netherlands Guiana --> use Surinam', code: 'sr' },
			{ name: 'Sweden', code: 'sw' },
			{ name: 'Switzerland', code: 'sz' },
			{ name: 'Syria', code: 'sy' },
			{ name: 'Syrian Arab Republic --> use Syria', code: 'sy' },
			{ name: 'Tajikistan', code: 'ta' },
			{ name: 'Tadzhik S.S.R. --> use Tajikistan', code: 'ta' },
			{ name: 'Tajik S.S.R. --> use Tajikistan', code: 'ta' },
			{ name: 'Tanzania', code: 'tz' },
			{ name: 'Pemba --> use Tanzania', code: 'tz' },
			{ name: 'Tanganyika --> use Tanzania', code: 'tz' },
			{ name: 'Zanzibar --> use Tanzania', code: 'tz' },
			{ name: 'Tasmania', code: 'tma' },
			{ name: 'Tennessee', code: 'tnu' },
			{ name: 'Terres australes et antarctiques françaises', code: 'fs' },
			{ name: 'Amsterdam Island --> use Terres australes et antarctiques françaises', code: 'fs' },
			{ name: 'Crozet Island --> use Terres australes et antarctiques françaises', code: 'fs' },
			{ name: 'French Southern and Antarctic Lands --> use Terres australes et antarctiques françaises', code: 'fs' },
			{ name: 'Kerguelen Island --> use Terres australes et antarctiques françaises', code: 'fs' },
			{ name: 'Saint Paul Island --> use Terres australes et antarctiques françaises', code: 'fs' },
			{ name: 'T.A.A.F. --> use Terres australes et antarctiques françaises', code: 'fs' },
			{ name: 'Texas', code: 'txu' },
			{ name: 'Thailand', code: 'th' },
			{ name: 'Siam --> use Thailand', code: 'th' },
			{ name: 'Timor-Leste', code: 'em' },
			{ name: 'Atauro, Ilha de --> use Timor-Leste', code: 'em' },
			{ name: 'East Timor --> use Timor-Leste', code: 'em' },
			{ name: 'Ilha de Atauro --> use Timor-Leste', code: 'em' },
			{ name: 'Ilheu de Jaco --> use Timor-Leste', code: 'em' },
			{ name: 'Jaco, Ilheu de --> use Timor-Leste', code: 'em' },
			{ name: 'Oe-Cussi --> use Timor-Leste', code: 'em' },
			{ name: 'Portuguese Timor --> use Timor-Leste', code: 'em' },
			{ name: 'Timor, East --> use Timor-Leste', code: 'em' },
			{ name: 'Togo', code: 'tg' },
			{ name: 'Tokelau', code: 'tl' },
			{ name: 'Atafu Atoll --> use Tokelau', code: 'tl' },
			{ name: 'Fakaofu Atoll --> use Tokelau', code: 'tl' },
			{ name: 'Nukunono Atoll --> use Tokelau', code: 'tl' },
			{ name: 'Union Islands --> use Tokelau', code: 'tl' },
			{ name: 'Tonga', code: 'to' },
			{ name: 'Friendly Islands --> use Tonga', code: 'to' },
			{ name: 'Haapai --> use Tonga', code: 'to' },
			{ name: 'Lulunga --> use Tonga', code: 'to' },
			{ name: 'Nomuka --> use Tonga', code: 'to' },
			{ name: 'Otu Tolu --> use Tonga', code: 'to' },
			{ name: 'Tongatapu --> use Tonga', code: 'to' },
			{ name: 'Vavau --> use Tonga', code: 'to' },
			{ name: 'Trinidad and Tobago', code: 'tr' },
			{ name: 'Tobago --> use Trinidad and Tobago', code: 'tr' },
			{ name: 'Tunisia', code: 'ti' },
			{ name: 'Turkey', code: 'tu' },
			{ name: 'Turkmenistan', code: 'tk' },
			{ name: 'Turkmen S.S.R. --> use Turkmenistan', code: 'tk' },
			{ name: 'Turks and Caicos Islands', code: 'tc' },
			{ name: 'Caicos Islands --> use Turks and Caicos Islands', code: 'tc' },
			{ name: 'Tuvalu', code: 'tv' },
			{ name: 'Ellice Islands --> use Tuvalu', code: 'tv' },
			{ name: 'Funafuti Atoll --> use Tuvalu', code: 'tv' },
			{ name: 'Gilbert and Ellice Islands --> use Tuvalu', code: 'tv' },
			{ name: 'Niulakita Island --> use Tuvalu', code: 'tv' },
			{ name: 'Nukufetau Atoll --> use Tuvalu', code: 'tv' },
			{ name: 'Nukulaelae Atoll --> use Tuvalu', code: 'tv' },
			{ name: 'Nukulailai Atoll --> use Tuvalu', code: 'tv' },
			{ name: 'Nurakita Island --> use Tuvalu', code: 'tv' },
			{ name: 'Uganda', code: 'ug' },
			{ name: 'Ukraine', code: 'un' },
			{ name: 'United Arab Emirates', code: 'ts' },
			{ name: 'Abu Dhabi --> use United Arab Emirates', code: 'ts' },
			{ name: 'Abu Zaby --> use United Arab Emirates', code: 'ts' },
			{ name: '`Ajman --> use United Arab Emirates', code: 'ts' },
			{ name: 'Dubai --> use United Arab Emirates', code: 'ts' },
			{ name: 'Dubayy --> use United Arab Emirates', code: 'ts' },
			{ name: 'Fujairah --> use United Arab Emirates', code: 'ts' },
			{ name: 'Fujayrah --> use United Arab Emirates', code: 'ts' },
			{ name: 'Kalba --> use United Arab Emirates', code: 'ts' },
			{ name: 'Oman, Trucial --> use United Arab Emirates', code: 'ts' },
			{ name: 'Ras al Khaimah --> use United Arab Emirates', code: 'ts' },
			{ name: 'Ra\'s al-Khaymah --> use United Arab Emirates', code: 'ts' },
			{ name: 'Shariqah --> use United Arab Emirates', code: 'ts' },
			{ name: 'Sharjah --> use United Arab Emirates', code: 'ts' },
			{ name: 'Trucial Coast --> use United Arab Emirates', code: 'ts' },
			{ name: 'Trucial Oman --> use United Arab Emirates', code: 'ts' },
			{ name: 'Trucial Sheikdoms --> use United Arab Emirates', code: 'ts' },
			{ name: 'Trucial States --> use United Arab Emirates', code: 'ts' },
			{ name: 'Umm al Qaiwain --> use United Arab Emirates', code: 'ts' },
			{ name: 'Umm al-Qaywayn --> use United Arab Emirates', code: 'ts' },
			{ name: 'United Kingdom', code: 'xxk' },
			{ name: 'Great Britain --> use United Kingdom', code: 'xxk' },
			{ name: 'United States', code: 'xxu' },
			{ name: 'United States Misc. Caribbean Islands', code: 'uc' },
			{ name: 'Navassa Island --> use United States Misc. Caribbean Islands', code: 'uc' },
			{ name: 'Quita Sueno Bank --> use United States Misc. Caribbean Islands', code: 'uc' },
			{ name: 'Roncador Cay --> use United States Misc. Caribbean Islands', code: 'uc' },
			{ name: 'United States Misc. Pacific Islands', code: 'up' },
			{ name: 'Baker Island --> use United States Misc. Pacific Islands', code: 'up' },
			{ name: 'Howland Island --> use United States Misc. Pacific Islands', code: 'up' },
			{ name: 'Jarvis Island --> use United States Misc. Pacific Islands', code: 'up' },
			{ name: 'Kingman Reef --> use United States Misc. Pacific Islands', code: 'up' },
			{ name: 'Palmyra Atoll --> use United States Misc. Pacific Islands', code: 'up' },
			{ name: 'Uruguay', code: 'uy' },
			{ name: 'Utah', code: 'utu' },
			{ name: 'Uzbekistan', code: 'uz' },
			{ name: 'Uzbek S.S.R. --> use Uzbekistan', code: 'uz' },
			{ name: 'Vanuatu', code: 'nn' },
			{ name: 'Banks Islands --> use Vanuatu', code: 'nn' },
			{ name: 'New Hebrides --> use Vanuatu', code: 'nn' },
			{ name: 'Torres Islands --> use Vanuatu', code: 'nn' },
			{ name: 'Various places', code: 'vp' },
			{ name: 'Vatican City', code: 'vc' },
			{ name: 'Holy See --> use Vatican City', code: 'vc' },
			{ name: 'Venezuela', code: 've' },
			{ name: 'Vermont', code: 'vtu' },
			{ name: 'Victoria', code: 'vra' },
			{ name: 'Vietnam', code: 'vm' },
			{ name: 'Democratic People\'s Republic of Vietnam --> use Vietnam', code: 'vm' },
			{ name: 'North Vietnam --> use Vietnam', code: 'vm' },
			{ name: 'South Vietnam --> use Vietnam', code: 'vm' },
			{ name: 'Vietnam, North --> use Vietnam', code: 'vm' },
			{ name: 'Vietnam, Republic of --> use Vietnam', code: 'vm' },
			{ name: 'Vietnam, South --> use Vietnam', code: 'vm' },
			{ name: 'Virgin Islands of the United States', code: 'vi' },
			{ name: 'Virginia', code: 'vau' },
			{ name: 'Wake Island', code: 'wk' },
			{ name: 'Wales', code: 'wlk' },
			{ name: 'Wallis and Futuna', code: 'wf' },
			{ name: 'Alofi --> use Wallis and Futuna', code: 'wf' },
			{ name: 'Futuna --> use Wallis and Futuna', code: 'wf' },
			{ name: 'Horne, Iles de --> use Wallis and Futuna', code: 'wf' },
			{ name: 'Ile Uvea (Wallis and Futuna) --> use Wallis and Futuna', code: 'wf' },
			{ name: 'Iles de Horne --> use Wallis and Futuna', code: 'wf' },
			{ name: 'Uvea (Wallis and Futuna) --> use Wallis and Futuna', code: 'wf' },
			{ name: 'Washington (State)', code: 'wau' },
			{ name: 'West Bank of the Jordan River', code: 'wj' },
			{ name: 'Jordan (Territory under Israeli occupation, 1967- ) --> use West Bank of the Jordan River', code: 'wj' },
			{ name: 'West Virginia', code: 'wvu' },
			{ name: 'Western Australia', code: 'wea' },
			{ name: 'Western Sahara ', code: 'ss' },
			{ name: 'Río de Oro --> use Western Sahara ', code: 'ss' },
			{ name: 'Saguia el Hamra --> use Western Sahara ', code: 'ss' },
			{ name: 'Spanish Sahara --> use Western Sahara ', code: 'ss' },
			{ name: 'Wisconsin', code: 'wiu' },
			{ name: 'Wyoming', code: 'wyu' },
			{ name: 'Yemen', code: 'ye' },
			{ name: 'Aden --> use Yemen', code: 'ye' },
			{ name: 'Aden (Protectorate) --> use Yemen', code: 'ye' },
			{ name: 'Arab Republic of Yemen --> use Yemen', code: 'ye' },
			{ name: 'Federation of South Arabia --> use Yemen', code: 'ye' },
			{ name: 'Kamaran --> use Yemen', code: 'ye' },
			{ name: 'Perim --> use Yemen', code: 'ye' },
			{ name: 'Protectorate of South Arabia --> use Yemen', code: 'ye' },
			{ name: 'Socotra --> use Yemen', code: 'ye' },
			{ name: 'South Arabia --> use Yemen', code: 'ye' },
			{ name: 'Southern Yemen --> use Yemen', code: 'ye' },
			{ name: 'Yemen (People\'s Democratic Republic) --> use Yemen', code: 'ye' },
			{ name: 'Yukon Territory', code: 'ykc' },
			{ name: 'Zambia', code: 'za' },
			{ name: 'Northern Rhodesia --> use Zambia', code: 'za' },
			{ name: 'Zimbabwe', code: 'rh' },
			{ name: 'Rhodesia --> use Zimbabwe', code: 'rh' },
			{ name: 'Southern Rhodesia --> use Zimbabwe', code: 'rh' },
			{ name: 'Zimbabwe Rhodesia --> use Zimbabwe', code: 'rh' }
		];

		// removed

			// { name: 'Armenian S.S.R. --> use Armenia (Republic)', code: 'ai' },
			// { name: 'Soviet Union --> use Armenia (Republic)', code: 'ai' },
			// { name: 'Azerbaijan S.S.R. --> use Azerbaijan', code: 'aj' },
			// { name: 'Georgian S.S.R. --> use Georgia (Republic)', code: 'gs' },
			// { name: 'Soviet Union --> use Georgia (Republic)', code: 'gs' },
			// { name: 'Soviet Union --> use Azerbaijan', code: 'aj' },
			// { name: 'Soviet Union --> use Belarus', code: 'bw' },
			// { name: 'Soviet Union --> use Kyrgyzstan', code: 'kg' },
			// { name: 'Soviet Union --> use Moldova', code: 'mv' },
			// { name: 'Soviet Union --> use Turkmenistan', code: 'tk' },
			// { name: 'Soviet Union --> use Kazakhstan', code: 'kz' },
			// { name: 'Soviet Union --> use Tajikistan', code: 'ta' },
			// { name: 'Soviet Union --> use Uzbekistan', code: 'uz' },



		 var servicePlace = {
            getPubplaces: getPubplaces
        	};

        return servicePlace;

	   function getPubplaces() {
            return pubplaces;
        }

	}

})();